// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file teams/v1/private/teams.proto (package teams.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message teams.v1.private.Team
 */
export const Team = proto3.makeMessageType(
  "teams.v1.private.Team",
  () => [
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message teams.v1.private.CreateTeamRequest
 */
export const CreateTeamRequest = proto3.makeMessageType(
  "teams.v1.private.CreateTeamRequest",
  () => [
    { no: 1, name: "team", kind: "message", T: Team },
  ],
);

/**
 * @generated from message teams.v1.private.CreateTeamResponse
 */
export const CreateTeamResponse = proto3.makeMessageType(
  "teams.v1.private.CreateTeamResponse",
  () => [
    { no: 1, name: "team", kind: "message", T: Team },
  ],
);

