// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file teams/v1/private/teams.proto (package teams.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateTeamRequest, CreateTeamResponse, ListTeamsRequest, ListTeamsResponse} from "./teams_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service teams.v1.private.PrivateTeamsService
 */
export declare const PrivateTeamsService: {
  readonly typeName: "teams.v1.private.PrivateTeamsService",
  readonly methods: {
    /**
     * @generated from rpc teams.v1.private.PrivateTeamsService.CreateTeam
     */
    readonly createTeam: {
      readonly name: "CreateTeam",
      readonly I: typeof CreateTeamRequest,
      readonly O: typeof CreateTeamResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc teams.v1.private.PrivateTeamsService.ListTeams
     */
    readonly listTeams: {
      readonly name: "ListTeams",
      readonly I: typeof ListTeamsRequest,
      readonly O: typeof ListTeamsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

