// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file teams/v1/private/teams.proto (package teams.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateTeamRequest, CreateTeamResponse, ListTeamsRequest, ListTeamsResponse} from "./teams_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service teams.v1.private.PrivateTeamsService
 */
export const PrivateTeamsService = {
  typeName: "teams.v1.private.PrivateTeamsService",
  methods: {
    /**
     * @generated from rpc teams.v1.private.PrivateTeamsService.CreateTeam
     */
    createTeam: {
      name: "CreateTeam",
      I: CreateTeamRequest,
      O: CreateTeamResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc teams.v1.private.PrivateTeamsService.ListTeams
     */
    listTeams: {
      name: "ListTeams",
      I: ListTeamsRequest,
      O: ListTeamsResponse,
      kind: MethodKind.Unary,
    },
  }
};

