// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file remote-scoring/v1/private/remote-scoring.proto (package remote_scoring.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message remote_scoring.v1.private.UploadScoreRequest
 */
export declare class UploadScoreRequest extends Message<UploadScoreRequest> {
  /**
   * @generated from field: string team_one_id = 1;
   */
  teamOneId: string;

  /**
   * @generated from field: string team_two_id = 2;
   */
  teamTwoId: string;

  /**
   * @generated from field: int32 team_one_score = 3;
   */
  teamOneScore: number;

  /**
   * @generated from field: int32 team_two_score = 4;
   */
  teamTwoScore: number;

  /**
   * @generated from field: google.protobuf.Timestamp played_at = 5;
   */
  playedAt?: Timestamp;

  constructor(data?: PartialMessage<UploadScoreRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "remote_scoring.v1.private.UploadScoreRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadScoreRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadScoreRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadScoreRequest;

  static equals(a: UploadScoreRequest | PlainMessage<UploadScoreRequest> | undefined, b: UploadScoreRequest | PlainMessage<UploadScoreRequest> | undefined): boolean;
}

/**
 * @generated from message remote_scoring.v1.private.UploadScoreResponse
 */
export declare class UploadScoreResponse extends Message<UploadScoreResponse> {
  constructor(data?: PartialMessage<UploadScoreResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "remote_scoring.v1.private.UploadScoreResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadScoreResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadScoreResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadScoreResponse;

  static equals(a: UploadScoreResponse | PlainMessage<UploadScoreResponse> | undefined, b: UploadScoreResponse | PlainMessage<UploadScoreResponse> | undefined): boolean;
}

/**
 * @generated from message remote_scoring.v1.private.ListScoresRequest
 */
export declare class ListScoresRequest extends Message<ListScoresRequest> {
  /**
   * @generated from field: google.protobuf.Timestamp date = 1;
   */
  date?: Timestamp;

  constructor(data?: PartialMessage<ListScoresRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "remote_scoring.v1.private.ListScoresRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListScoresRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListScoresRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListScoresRequest;

  static equals(a: ListScoresRequest | PlainMessage<ListScoresRequest> | undefined, b: ListScoresRequest | PlainMessage<ListScoresRequest> | undefined): boolean;
}

/**
 * @generated from message remote_scoring.v1.private.ListScoresResponse
 */
export declare class ListScoresResponse extends Message<ListScoresResponse> {
  /**
   * @generated from field: repeated remote_scoring.v1.private.ListScoresResponse.Score scores = 1;
   */
  scores: ListScoresResponse_Score[];

  constructor(data?: PartialMessage<ListScoresResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "remote_scoring.v1.private.ListScoresResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListScoresResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListScoresResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListScoresResponse;

  static equals(a: ListScoresResponse | PlainMessage<ListScoresResponse> | undefined, b: ListScoresResponse | PlainMessage<ListScoresResponse> | undefined): boolean;
}

/**
 * @generated from message remote_scoring.v1.private.ListScoresResponse.Score
 */
export declare class ListScoresResponse_Score extends Message<ListScoresResponse_Score> {
  /**
   * @generated from field: string team_one_id = 1;
   */
  teamOneId: string;

  /**
   * @generated from field: string team_two_id = 2;
   */
  teamTwoId: string;

  /**
   * @generated from field: int32 team_one_score = 3;
   */
  teamOneScore: number;

  /**
   * @generated from field: int32 team_two_score = 4;
   */
  teamTwoScore: number;

  /**
   * @generated from field: google.protobuf.Timestamp played_at = 5;
   */
  playedAt?: Timestamp;

  constructor(data?: PartialMessage<ListScoresResponse_Score>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "remote_scoring.v1.private.ListScoresResponse.Score";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListScoresResponse_Score;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListScoresResponse_Score;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListScoresResponse_Score;

  static equals(a: ListScoresResponse_Score | PlainMessage<ListScoresResponse_Score> | undefined, b: ListScoresResponse_Score | PlainMessage<ListScoresResponse_Score> | undefined): boolean;
}

