// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file remote-scoring/v1/private/remote-scoring.proto (package remote_scoring.v1.private, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file remote-scoring/v1/private/remote-scoring.proto.
 */
export declare const file_remote_scoring_v1_private_remote_scoring: GenFile;

/**
 * @generated from message remote_scoring.v1.private.UploadScoreRequest
 */
export declare type UploadScoreRequest = Message<"remote_scoring.v1.private.UploadScoreRequest"> & {
  /**
   * @generated from field: string team_one_id = 1;
   */
  teamOneId: string;

  /**
   * @generated from field: string team_two_id = 2;
   */
  teamTwoId: string;

  /**
   * @generated from field: int32 team_one_score = 3;
   */
  teamOneScore: number;

  /**
   * @generated from field: int32 team_two_score = 4;
   */
  teamTwoScore: number;

  /**
   * @generated from field: google.protobuf.Timestamp played_at = 5;
   */
  playedAt?: Timestamp;
};

/**
 * Describes the message remote_scoring.v1.private.UploadScoreRequest.
 * Use `create(UploadScoreRequestSchema)` to create a new message.
 */
export declare const UploadScoreRequestSchema: GenMessage<UploadScoreRequest>;

/**
 * @generated from message remote_scoring.v1.private.UploadScoreResponse
 */
export declare type UploadScoreResponse = Message<"remote_scoring.v1.private.UploadScoreResponse"> & {
  /**
   * @generated from field: string score_id = 1;
   */
  scoreId: string;
};

/**
 * Describes the message remote_scoring.v1.private.UploadScoreResponse.
 * Use `create(UploadScoreResponseSchema)` to create a new message.
 */
export declare const UploadScoreResponseSchema: GenMessage<UploadScoreResponse>;

/**
 * @generated from message remote_scoring.v1.private.ListScoresFilter
 */
export declare type ListScoresFilter = Message<"remote_scoring.v1.private.ListScoresFilter"> & {
  /**
   * @generated from field: google.protobuf.Timestamp recorded_date = 1;
   */
  recordedDate?: Timestamp;

  /**
   * @generated from field: repeated string team_ids = 2;
   */
  teamIds: string[];
};

/**
 * Describes the message remote_scoring.v1.private.ListScoresFilter.
 * Use `create(ListScoresFilterSchema)` to create a new message.
 */
export declare const ListScoresFilterSchema: GenMessage<ListScoresFilter>;

/**
 * @generated from message remote_scoring.v1.private.ListScoresRequest
 */
export declare type ListScoresRequest = Message<"remote_scoring.v1.private.ListScoresRequest"> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 pageSize = 3;
   */
  pageSize?: number;

  /**
   * @generated from field: optional remote_scoring.v1.private.ListScoresFilter score_filter = 4;
   */
  scoreFilter?: ListScoresFilter;
};

/**
 * Describes the message remote_scoring.v1.private.ListScoresRequest.
 * Use `create(ListScoresRequestSchema)` to create a new message.
 */
export declare const ListScoresRequestSchema: GenMessage<ListScoresRequest>;

/**
 * @generated from message remote_scoring.v1.private.ListScoresResponse
 */
export declare type ListScoresResponse = Message<"remote_scoring.v1.private.ListScoresResponse"> & {
  /**
   * @generated from field: repeated remote_scoring.v1.private.ListScoresResponse.Score scores = 1;
   */
  scores: ListScoresResponse_Score[];

  /**
   * @generated from field: int32 total_count = 2;
   */
  totalCount: number;
};

/**
 * Describes the message remote_scoring.v1.private.ListScoresResponse.
 * Use `create(ListScoresResponseSchema)` to create a new message.
 */
export declare const ListScoresResponseSchema: GenMessage<ListScoresResponse>;

/**
 * @generated from message remote_scoring.v1.private.ListScoresResponse.Score
 */
export declare type ListScoresResponse_Score = Message<"remote_scoring.v1.private.ListScoresResponse.Score"> & {
  /**
   * @generated from field: string score_id = 1;
   */
  scoreId: string;

  /**
   * @generated from field: string team_one_id = 2;
   */
  teamOneId: string;

  /**
   * @generated from field: string team_two_id = 3;
   */
  teamTwoId: string;

  /**
   * @generated from field: int32 team_one_score = 4;
   */
  teamOneScore: number;

  /**
   * @generated from field: int32 team_two_score = 5;
   */
  teamTwoScore: number;

  /**
   * @generated from field: google.protobuf.Timestamp played_at = 6;
   */
  playedAt?: Timestamp;
};

/**
 * Describes the message remote_scoring.v1.private.ListScoresResponse.Score.
 * Use `create(ListScoresResponse_ScoreSchema)` to create a new message.
 */
export declare const ListScoresResponse_ScoreSchema: GenMessage<ListScoresResponse_Score>;

/**
 * @generated from message remote_scoring.v1.private.DeleteScoreRequest
 */
export declare type DeleteScoreRequest = Message<"remote_scoring.v1.private.DeleteScoreRequest"> & {
  /**
   * @generated from field: string score_id = 1;
   */
  scoreId: string;
};

/**
 * Describes the message remote_scoring.v1.private.DeleteScoreRequest.
 * Use `create(DeleteScoreRequestSchema)` to create a new message.
 */
export declare const DeleteScoreRequestSchema: GenMessage<DeleteScoreRequest>;

/**
 * @generated from message remote_scoring.v1.private.DeleteScoreResponse
 */
export declare type DeleteScoreResponse = Message<"remote_scoring.v1.private.DeleteScoreResponse"> & {
};

/**
 * Describes the message remote_scoring.v1.private.DeleteScoreResponse.
 * Use `create(DeleteScoreResponseSchema)` to create a new message.
 */
export declare const DeleteScoreResponseSchema: GenMessage<DeleteScoreResponse>;

/**
 * @generated from message remote_scoring.v1.private.UpdateScoreRequest
 */
export declare type UpdateScoreRequest = Message<"remote_scoring.v1.private.UpdateScoreRequest"> & {
  /**
   * @generated from field: string score_id = 1;
   */
  scoreId: string;

  /**
   * @generated from field: string team_one_id = 2;
   */
  teamOneId: string;

  /**
   * @generated from field: string team_two_id = 3;
   */
  teamTwoId: string;

  /**
   * @generated from field: int32 team_one_score = 4;
   */
  teamOneScore: number;

  /**
   * @generated from field: int32 team_two_score = 5;
   */
  teamTwoScore: number;

  /**
   * @generated from field: google.protobuf.Timestamp played_at = 6;
   */
  playedAt?: Timestamp;
};

/**
 * Describes the message remote_scoring.v1.private.UpdateScoreRequest.
 * Use `create(UpdateScoreRequestSchema)` to create a new message.
 */
export declare const UpdateScoreRequestSchema: GenMessage<UpdateScoreRequest>;

/**
 * @generated from message remote_scoring.v1.private.UpdateScoreResponse
 */
export declare type UpdateScoreResponse = Message<"remote_scoring.v1.private.UpdateScoreResponse"> & {
};

/**
 * Describes the message remote_scoring.v1.private.UpdateScoreResponse.
 * Use `create(UpdateScoreResponseSchema)` to create a new message.
 */
export declare const UpdateScoreResponseSchema: GenMessage<UpdateScoreResponse>;

/**
 * @generated from service remote_scoring.v1.private.PrivateRemoteScoringService
 */
export declare const PrivateRemoteScoringService: GenService<{
  /**
   * @generated from rpc remote_scoring.v1.private.PrivateRemoteScoringService.UploadScore
   */
  uploadScore: {
    methodKind: "unary";
    input: typeof UploadScoreRequestSchema;
    output: typeof UploadScoreResponseSchema;
  },
  /**
   * @generated from rpc remote_scoring.v1.private.PrivateRemoteScoringService.ListScores
   */
  listScores: {
    methodKind: "unary";
    input: typeof ListScoresRequestSchema;
    output: typeof ListScoresResponseSchema;
  },
  /**
   * @generated from rpc remote_scoring.v1.private.PrivateRemoteScoringService.DeleteScore
   */
  deleteScore: {
    methodKind: "unary";
    input: typeof DeleteScoreRequestSchema;
    output: typeof DeleteScoreResponseSchema;
  },
  /**
   * @generated from rpc remote_scoring.v1.private.PrivateRemoteScoringService.UpdateScore
   */
  updateScore: {
    methodKind: "unary";
    input: typeof UpdateScoreRequestSchema;
    output: typeof UpdateScoreResponseSchema;
  },
}>;

