// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file subscriptions/v1/public/subscriptions.proto (package subscriptions.v1.public, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSubscriptionPlansRequest, GetSubscriptionPlansResponse } from "./subscriptions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service subscriptions.v1.public.PublicSubscriptionsService
 */
export declare const PublicSubscriptionsService: {
  readonly typeName: "subscriptions.v1.public.PublicSubscriptionsService",
  readonly methods: {
    /**
     * @generated from rpc subscriptions.v1.public.PublicSubscriptionsService.GetSubscriptionPlans
     */
    readonly getSubscriptionPlans: {
      readonly name: "GetSubscriptionPlans",
      readonly I: typeof GetSubscriptionPlansRequest,
      readonly O: typeof GetSubscriptionPlansResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

