// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=js+dts"
// @generated from file divisions/v1/private/divisions.proto (package divisions.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddDivisionRequest, AddDivisionResponse, GetDivisionRequest, GetDivisionResponse, ListDivisionsRequest, ListDivisionsResponse, RemoveDivisionsRequest, RemoveDivisionsResponse, UpdateDivisionRequest, UpdateDivisionResponse } from "./divisions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service divisions.v1.private.PrivateDivisionsService
 */
export const PrivateDivisionsService = {
  typeName: "divisions.v1.private.PrivateDivisionsService",
  methods: {
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.AddDivision
     */
    addDivision: {
      name: "AddDivision",
      I: AddDivisionRequest,
      O: AddDivisionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.RemoveDivisions
     */
    removeDivisions: {
      name: "RemoveDivisions",
      I: RemoveDivisionsRequest,
      O: RemoveDivisionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.ListDivisions
     */
    listDivisions: {
      name: "ListDivisions",
      I: ListDivisionsRequest,
      O: ListDivisionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.UpdateDivision
     */
    updateDivision: {
      name: "UpdateDivision",
      I: UpdateDivisionRequest,
      O: UpdateDivisionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.GetDivision
     */
    getDivision: {
      name: "GetDivision",
      I: GetDivisionRequest,
      O: GetDivisionResponse,
      kind: MethodKind.Unary,
    },
  }
};

