// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=js+dts"
// @generated from file divisions/v1/private/divisions.proto (package divisions.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddDivisionRequest, AddDivisionResponse, GetDivisionRequest, GetDivisionResponse, ListDivisionsRequest, ListDivisionsResponse, RemoveDivisionsRequest, RemoveDivisionsResponse, UpdateDivisionRequest, UpdateDivisionResponse } from "./divisions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc divisions.v1.private.PrivateDivisionsService.AddDivision
 */
export const addDivision: {
      readonly name: "AddDivision",
      readonly I: typeof AddDivisionRequest,
      readonly O: typeof AddDivisionResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "divisions.v1.private.PrivateDivisionsService"
  }
};
/**
 * @generated from rpc divisions.v1.private.PrivateDivisionsService.RemoveDivisions
 */
export const removeDivisions: {
      readonly name: "RemoveDivisions",
      readonly I: typeof RemoveDivisionsRequest,
      readonly O: typeof RemoveDivisionsResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "divisions.v1.private.PrivateDivisionsService"
  }
};
/**
 * @generated from rpc divisions.v1.private.PrivateDivisionsService.ListDivisions
 */
export const listDivisions: {
      readonly name: "ListDivisions",
      readonly I: typeof ListDivisionsRequest,
      readonly O: typeof ListDivisionsResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "divisions.v1.private.PrivateDivisionsService"
  }
};
/**
 * @generated from rpc divisions.v1.private.PrivateDivisionsService.UpdateDivision
 */
export const updateDivision: {
      readonly name: "UpdateDivision",
      readonly I: typeof UpdateDivisionRequest,
      readonly O: typeof UpdateDivisionResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "divisions.v1.private.PrivateDivisionsService"
  }
};
/**
 * @generated from rpc divisions.v1.private.PrivateDivisionsService.GetDivision
 */
export const getDivision: {
      readonly name: "GetDivision",
      readonly I: typeof GetDivisionRequest,
      readonly O: typeof GetDivisionResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "divisions.v1.private.PrivateDivisionsService"
  }
};
