// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file divisions/v1/private/divisions.proto (package divisions.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddDivisionRequest, AddDivisionResponse, GetDivisionRequest, GetDivisionResponse, ListDivisionsRequest, ListDivisionsResponse, RemoveDivisionsRequest, RemoveDivisionsResponse, UpdateDivisionRequest, UpdateDivisionResponse } from "./divisions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service divisions.v1.private.PrivateDivisionsService
 */
export declare const PrivateDivisionsService: {
  readonly typeName: "divisions.v1.private.PrivateDivisionsService",
  readonly methods: {
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.AddDivision
     */
    readonly addDivision: {
      readonly name: "AddDivision",
      readonly I: typeof AddDivisionRequest,
      readonly O: typeof AddDivisionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.RemoveDivisions
     */
    readonly removeDivisions: {
      readonly name: "RemoveDivisions",
      readonly I: typeof RemoveDivisionsRequest,
      readonly O: typeof RemoveDivisionsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.ListDivisions
     */
    readonly listDivisions: {
      readonly name: "ListDivisions",
      readonly I: typeof ListDivisionsRequest,
      readonly O: typeof ListDivisionsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.UpdateDivision
     */
    readonly updateDivision: {
      readonly name: "UpdateDivision",
      readonly I: typeof UpdateDivisionRequest,
      readonly O: typeof UpdateDivisionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc divisions.v1.private.PrivateDivisionsService.GetDivision
     */
    readonly getDivision: {
      readonly name: "GetDivision",
      readonly I: typeof GetDivisionRequest,
      readonly O: typeof GetDivisionResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

