// @generated by protoc-gen-es v0.2.0 with parameter "target=js"
// @generated from file busdriver/v1/busdriver.proto (package busdriver.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message busdriver.v1.GetMeRequest
 */
export const GetMeRequest = proto3.makeMessageType(
  "busdriver.v1.GetMeRequest",
  [],
);

/**
 * @generated from message busdriver.v1.GetMeResponse
 */
export const GetMeResponse = proto3.makeMessageType(
  "busdriver.v1.GetMeResponse",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

