// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file add-ons/v1/private/add-ons.proto (package addons.v1.private, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file add-ons/v1/private/add-ons.proto.
 */
export const file_add_ons_v1_private_add_ons = /*@__PURE__*/
  fileDesc("CiBhZGQtb25zL3YxL3ByaXZhdGUvYWRkLW9ucy5wcm90bxIRYWRkb25zLnYxLnByaXZhdGUiRgoSRW5hYmxlQWRkb25SZXF1ZXN0EjAKCmFkZG9uX3R5cGUYASABKA4yHC5hZGRvbnMudjEucHJpdmF0ZS5BZGRvblR5cGUiFQoTRW5hYmxlQWRkb25SZXNwb25zZSJKCgVBZGRvbhIwCgphZGRvbl90eXBlGAEgASgOMhwuYWRkb25zLnYxLnByaXZhdGUuQWRkb25UeXBlEg8KB2VuYWJsZWQYAiABKAgiEwoRTGlzdEFkZG9uc1JlcXVlc3QiPgoSTGlzdEFkZG9uc1Jlc3BvbnNlEigKBmFkZG9ucxgBIAMoCzIYLmFkZG9ucy52MS5wcml2YXRlLkFkZG9uIkcKE0Rpc2FibGVBZGRvblJlcXVlc3QSMAoKYWRkb25fdHlwZRgBIAEoDjIcLmFkZG9ucy52MS5wcml2YXRlLkFkZG9uVHlwZSIWChREaXNhYmxlQWRkb25SZXNwb25zZSpGCglBZGRvblR5cGUSGgoWQURET05fVFlQRV9VTlNQRUNJRklFRBAAEh0KGUFERE9OX1RZUEVfUkVNT1RFX1NDT1JJTkcQATKwAgoUUHJpdmF0ZUFkZG9uc1NlcnZpY2USXAoLRW5hYmxlQWRkb24SJS5hZGRvbnMudjEucHJpdmF0ZS5FbmFibGVBZGRvblJlcXVlc3QaJi5hZGRvbnMudjEucHJpdmF0ZS5FbmFibGVBZGRvblJlc3BvbnNlEl8KDERpc2FibGVBZGRvbhImLmFkZG9ucy52MS5wcml2YXRlLkRpc2FibGVBZGRvblJlcXVlc3QaJy5hZGRvbnMudjEucHJpdmF0ZS5EaXNhYmxlQWRkb25SZXNwb25zZRJZCgpMaXN0QWRkb25zEiQuYWRkb25zLnYxLnByaXZhdGUuTGlzdEFkZG9uc1JlcXVlc3QaJS5hZGRvbnMudjEucHJpdmF0ZS5MaXN0QWRkb25zUmVzcG9uc2VCWVpXZ2l0aHViLmNvbS9rZWVnYW5jcmFpZ2NydWlja3NoYW5rL3ZvbGxleS1hcGktY29ubmVjdC9hZGQtb25zL3YxL3ByaXZhdGU7YWRkb25zdjFwcml2YXRlYgZwcm90bzM");

/**
 * Describes the message addons.v1.private.EnableAddonRequest.
 * Use `create(EnableAddonRequestSchema)` to create a new message.
 */
export const EnableAddonRequestSchema = /*@__PURE__*/
  messageDesc(file_add_ons_v1_private_add_ons, 0);

/**
 * Describes the message addons.v1.private.EnableAddonResponse.
 * Use `create(EnableAddonResponseSchema)` to create a new message.
 */
export const EnableAddonResponseSchema = /*@__PURE__*/
  messageDesc(file_add_ons_v1_private_add_ons, 1);

/**
 * Describes the message addons.v1.private.Addon.
 * Use `create(AddonSchema)` to create a new message.
 */
export const AddonSchema = /*@__PURE__*/
  messageDesc(file_add_ons_v1_private_add_ons, 2);

/**
 * Describes the message addons.v1.private.ListAddonsRequest.
 * Use `create(ListAddonsRequestSchema)` to create a new message.
 */
export const ListAddonsRequestSchema = /*@__PURE__*/
  messageDesc(file_add_ons_v1_private_add_ons, 3);

/**
 * Describes the message addons.v1.private.ListAddonsResponse.
 * Use `create(ListAddonsResponseSchema)` to create a new message.
 */
export const ListAddonsResponseSchema = /*@__PURE__*/
  messageDesc(file_add_ons_v1_private_add_ons, 4);

/**
 * Describes the message addons.v1.private.DisableAddonRequest.
 * Use `create(DisableAddonRequestSchema)` to create a new message.
 */
export const DisableAddonRequestSchema = /*@__PURE__*/
  messageDesc(file_add_ons_v1_private_add_ons, 5);

/**
 * Describes the message addons.v1.private.DisableAddonResponse.
 * Use `create(DisableAddonResponseSchema)` to create a new message.
 */
export const DisableAddonResponseSchema = /*@__PURE__*/
  messageDesc(file_add_ons_v1_private_add_ons, 6);

/**
 * Describes the enum addons.v1.private.AddonType.
 */
export const AddonTypeSchema = /*@__PURE__*/
  enumDesc(file_add_ons_v1_private_add_ons, 0);

/**
 * @generated from enum addons.v1.private.AddonType
 */
export const AddonType = /*@__PURE__*/
  tsEnum(AddonTypeSchema);

/**
 * @generated from service addons.v1.private.PrivateAddonsService
 */
export const PrivateAddonsService = /*@__PURE__*/
  serviceDesc(file_add_ons_v1_private_add_ons, 0);

