// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file add-ons/v1/private/add-ons.proto (package addons.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DisableAddonRequest, DisableAddonResponse, EnableAddonRequest, EnableAddonResponse, ListAddonsRequest, ListAddonsResponse } from "./add-ons_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service addons.v1.private.PrivateAddonsService
 */
export declare const PrivateAddonsService: {
  readonly typeName: "addons.v1.private.PrivateAddonsService",
  readonly methods: {
    /**
     * @generated from rpc addons.v1.private.PrivateAddonsService.EnableAddon
     */
    readonly enableAddon: {
      readonly name: "EnableAddon",
      readonly I: typeof EnableAddonRequest,
      readonly O: typeof EnableAddonResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc addons.v1.private.PrivateAddonsService.DisableAddon
     */
    readonly disableAddon: {
      readonly name: "DisableAddon",
      readonly I: typeof DisableAddonRequest,
      readonly O: typeof DisableAddonResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc addons.v1.private.PrivateAddonsService.ListAddons
     */
    readonly listAddons: {
      readonly name: "ListAddons",
      readonly I: typeof ListAddonsRequest,
      readonly O: typeof ListAddonsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

