// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file add-ons/v1/private/add_ons.proto (package addons.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EnableAddonRequest, EnableAddonResponse } from "./add_ons_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service addons.v1.private.PrivateAddonsService
 */
export declare const PrivateAddonsService: {
  readonly typeName: "addons.v1.private.PrivateAddonsService",
  readonly methods: {
    /**
     * @generated from rpc addons.v1.private.PrivateAddonsService.EnableAddon
     */
    readonly enableAddon: {
      readonly name: "EnableAddon",
      readonly I: typeof EnableAddonRequest,
      readonly O: typeof EnableAddonResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

