// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file grades/v1/private/grades.proto (package grades.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";

/**
 * @generated from message grades.v1.private.Grade
 */
export declare class Grade extends Message<Grade> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string organisation = 2;
   */
  organisation: string;

  /**
   * @generated from field: string grade_id = 3;
   */
  gradeId: string;

  constructor(data?: PartialMessage<Grade>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grades.v1.private.Grade";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Grade;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Grade;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Grade;

  static equals(a: Grade | PlainMessage<Grade> | undefined, b: Grade | PlainMessage<Grade> | undefined): boolean;
}

/**
 * @generated from message grades.v1.private.CreateGradeRequest
 */
export declare class CreateGradeRequest extends Message<CreateGradeRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<CreateGradeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grades.v1.private.CreateGradeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateGradeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateGradeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateGradeRequest;

  static equals(a: CreateGradeRequest | PlainMessage<CreateGradeRequest> | undefined, b: CreateGradeRequest | PlainMessage<CreateGradeRequest> | undefined): boolean;
}

/**
 * @generated from message grades.v1.private.CreateGradeResponse
 */
export declare class CreateGradeResponse extends Message<CreateGradeResponse> {
  /**
   * @generated from field: grades.v1.private.Grade grade = 1;
   */
  grade?: Grade;

  constructor(data?: PartialMessage<CreateGradeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grades.v1.private.CreateGradeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateGradeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateGradeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateGradeResponse;

  static equals(a: CreateGradeResponse | PlainMessage<CreateGradeResponse> | undefined, b: CreateGradeResponse | PlainMessage<CreateGradeResponse> | undefined): boolean;
}

/**
 * @generated from message grades.v1.private.ListGradesRequest
 */
export declare class ListGradesRequest extends Message<ListGradesRequest> {
  constructor(data?: PartialMessage<ListGradesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grades.v1.private.ListGradesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListGradesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListGradesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListGradesRequest;

  static equals(a: ListGradesRequest | PlainMessage<ListGradesRequest> | undefined, b: ListGradesRequest | PlainMessage<ListGradesRequest> | undefined): boolean;
}

/**
 * @generated from message grades.v1.private.ListGradesResponse
 */
export declare class ListGradesResponse extends Message<ListGradesResponse> {
  /**
   * @generated from field: repeated grades.v1.private.Grade grades = 1;
   */
  grades: Grade[];

  constructor(data?: PartialMessage<ListGradesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "grades.v1.private.ListGradesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListGradesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListGradesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListGradesResponse;

  static equals(a: ListGradesResponse | PlainMessage<ListGradesResponse> | undefined, b: ListGradesResponse | PlainMessage<ListGradesResponse> | undefined): boolean;
}

