// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file grades/v1/private/grades.proto (package grades.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateGradeRequest, CreateGradeResponse, ListGradesRequest, ListGradesResponse} from "./grades_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service grades.v1.private.PrivateGradesService
 */
export declare const PrivateGradesService: {
  readonly typeName: "grades.v1.private.PrivateGradesService",
  readonly methods: {
    /**
     * @generated from rpc grades.v1.private.PrivateGradesService.CreateGrade
     */
    readonly createGrade: {
      readonly name: "CreateGrade",
      readonly I: typeof CreateGradeRequest,
      readonly O: typeof CreateGradeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grades.v1.private.PrivateGradesService.ListGrades
     */
    readonly listGrades: {
      readonly name: "ListGrades",
      readonly I: typeof ListGradesRequest,
      readonly O: typeof ListGradesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

