// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file grades/v1/private/grades.proto (package grades.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateGradeRequest, CreateGradeResponse, ListGradesRequest, ListGradesResponse} from "./grades_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service grades.v1.private.PrivateTeamsService
 */
export const PrivateTeamsService = {
  typeName: "grades.v1.private.PrivateTeamsService",
  methods: {
    /**
     * @generated from rpc grades.v1.private.PrivateTeamsService.CreateGrade
     */
    createGrade: {
      name: "CreateGrade",
      I: CreateGradeRequest,
      O: CreateGradeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grades.v1.private.PrivateTeamsService.ListGrades
     */
    listGrades: {
      name: "ListGrades",
      I: ListGradesRequest,
      O: ListGradesResponse,
      kind: MethodKind.Unary,
    },
  }
};

