// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file grades/v1/private/grades.proto (package grades.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message grades.v1.private.Grade
 */
export const Grade = proto3.makeMessageType(
  "grades.v1.private.Grade",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "grade_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message grades.v1.private.CreateGradeRequest
 */
export const CreateGradeRequest = proto3.makeMessageType(
  "grades.v1.private.CreateGradeRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message grades.v1.private.CreateGradeResponse
 */
export const CreateGradeResponse = proto3.makeMessageType(
  "grades.v1.private.CreateGradeResponse",
  () => [
    { no: 1, name: "grade", kind: "message", T: Grade },
  ],
);

/**
 * @generated from message grades.v1.private.ListGradesRequest
 */
export const ListGradesRequest = proto3.makeMessageType(
  "grades.v1.private.ListGradesRequest",
  [],
);

/**
 * @generated from message grades.v1.private.ListGradesResponse
 */
export const ListGradesResponse = proto3.makeMessageType(
  "grades.v1.private.ListGradesResponse",
  () => [
    { no: 1, name: "grades", kind: "message", T: Grade, repeated: true },
  ],
);

