// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file scoring/v1/private/scoring.proto (package scoring.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UploadScoreRequest, UploadScoreResponse } from "./scoring_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scoring.v1.private.PrivateScoringService
 */
export const PrivateScoringService = {
  typeName: "scoring.v1.private.PrivateScoringService",
  methods: {
    /**
     * Common endpoints
     *
     * @generated from rpc scoring.v1.private.PrivateScoringService.UploadScore
     */
    uploadScore: {
      name: "UploadScore",
      I: UploadScoreRequest,
      O: UploadScoreResponse,
      kind: MethodKind.Unary,
    },
  }
};

