// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file scoring/v1/private/scoring.proto (package scoring.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message scoring.v1.private.UploadScoreRequest
 */
export declare class UploadScoreRequest extends Message<UploadScoreRequest> {
  /**
   * @generated from field: string team_one_id = 3;
   */
  teamOneId: string;

  /**
   * @generated from field: string team_two_id = 4;
   */
  teamTwoId: string;

  /**
   * @generated from field: int32 team_one_score = 5;
   */
  teamOneScore: number;

  /**
   * @generated from field: int32 team_two_score = 6;
   */
  teamTwoScore: number;

  constructor(data?: PartialMessage<UploadScoreRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "scoring.v1.private.UploadScoreRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadScoreRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadScoreRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadScoreRequest;

  static equals(a: UploadScoreRequest | PlainMessage<UploadScoreRequest> | undefined, b: UploadScoreRequest | PlainMessage<UploadScoreRequest> | undefined): boolean;
}

/**
 * @generated from message scoring.v1.private.UploadScoreResponse
 */
export declare class UploadScoreResponse extends Message<UploadScoreResponse> {
  constructor(data?: PartialMessage<UploadScoreResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "scoring.v1.private.UploadScoreResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadScoreResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadScoreResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadScoreResponse;

  static equals(a: UploadScoreResponse | PlainMessage<UploadScoreResponse> | undefined, b: UploadScoreResponse | PlainMessage<UploadScoreResponse> | undefined): boolean;
}

