// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file scoring/v1/private/scoring.proto (package scoring.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message scoring.v1.private.UploadScoreRequest
 */
export const UploadScoreRequest = /*@__PURE__*/ proto3.makeMessageType(
  "scoring.v1.private.UploadScoreRequest",
  () => [
    { no: 3, name: "team_one_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "team_two_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "team_one_score", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "team_two_score", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message scoring.v1.private.UploadScoreResponse
 */
export const UploadScoreResponse = /*@__PURE__*/ proto3.makeMessageType(
  "scoring.v1.private.UploadScoreResponse",
  [],
);

