// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file scoring/v1/private/scoring.proto (package scoring.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UploadScoreRequest, UploadScoreResponse } from "./scoring_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scoring.v1.private.PrivateScoringService
 */
export declare const PrivateScoringService: {
  readonly typeName: "scoring.v1.private.PrivateScoringService",
  readonly methods: {
    /**
     * Common endpoints
     *
     * @generated from rpc scoring.v1.private.PrivateScoringService.UploadScore
     */
    readonly uploadScore: {
      readonly name: "UploadScore",
      readonly I: typeof UploadScoreRequest,
      readonly O: typeof UploadScoreResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

