// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file playing-spaces/v1/private/playing-spaces.proto (package playing_spaces.v1.private, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file playing-spaces/v1/private/playing-spaces.proto.
 */
export declare const file_playing_spaces_v1_private_playing_spaces: GenFile;

/**
 * @generated from message playing_spaces.v1.private.PlayingSpace
 */
export declare type PlayingSpace = Message<"playing_spaces.v1.private.PlayingSpace"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string location_id = 2;
   */
  locationId: string;

  /**
   * @generated from field: string location_name = 3;
   */
  locationName: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;
};

/**
 * Describes the message playing_spaces.v1.private.PlayingSpace.
 * Use `create(PlayingSpaceSchema)` to create a new message.
 */
export declare const PlayingSpaceSchema: GenMessage<PlayingSpace>;

/**
 * @generated from message playing_spaces.v1.private.CreatePlayingSpaceRequest
 */
export declare type CreatePlayingSpaceRequest = Message<"playing_spaces.v1.private.CreatePlayingSpaceRequest"> & {
  /**
   * @generated from field: string location_id = 1;
   */
  locationId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message playing_spaces.v1.private.CreatePlayingSpaceRequest.
 * Use `create(CreatePlayingSpaceRequestSchema)` to create a new message.
 */
export declare const CreatePlayingSpaceRequestSchema: GenMessage<CreatePlayingSpaceRequest>;

/**
 * @generated from message playing_spaces.v1.private.CreatePlayingSpaceResponse
 */
export declare type CreatePlayingSpaceResponse = Message<"playing_spaces.v1.private.CreatePlayingSpaceResponse"> & {
  /**
   * @generated from field: playing_spaces.v1.private.PlayingSpace playingSpace = 1;
   */
  playingSpace?: PlayingSpace;
};

/**
 * Describes the message playing_spaces.v1.private.CreatePlayingSpaceResponse.
 * Use `create(CreatePlayingSpaceResponseSchema)` to create a new message.
 */
export declare const CreatePlayingSpaceResponseSchema: GenMessage<CreatePlayingSpaceResponse>;

/**
 * @generated from message playing_spaces.v1.private.RemovePlayingSpacesRequest
 */
export declare type RemovePlayingSpacesRequest = Message<"playing_spaces.v1.private.RemovePlayingSpacesRequest"> & {
  /**
   * @generated from field: repeated string playingSpaceIds = 1;
   */
  playingSpaceIds: string[];
};

/**
 * Describes the message playing_spaces.v1.private.RemovePlayingSpacesRequest.
 * Use `create(RemovePlayingSpacesRequestSchema)` to create a new message.
 */
export declare const RemovePlayingSpacesRequestSchema: GenMessage<RemovePlayingSpacesRequest>;

/**
 * @generated from message playing_spaces.v1.private.RemovePlayingSpacesResponse
 */
export declare type RemovePlayingSpacesResponse = Message<"playing_spaces.v1.private.RemovePlayingSpacesResponse"> & {
};

/**
 * Describes the message playing_spaces.v1.private.RemovePlayingSpacesResponse.
 * Use `create(RemovePlayingSpacesResponseSchema)` to create a new message.
 */
export declare const RemovePlayingSpacesResponseSchema: GenMessage<RemovePlayingSpacesResponse>;

/**
 * @generated from message playing_spaces.v1.private.ModifyPlayingSpaceRequest
 */
export declare type ModifyPlayingSpaceRequest = Message<"playing_spaces.v1.private.ModifyPlayingSpaceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string location_id = 3;
   */
  locationId?: string;
};

/**
 * Describes the message playing_spaces.v1.private.ModifyPlayingSpaceRequest.
 * Use `create(ModifyPlayingSpaceRequestSchema)` to create a new message.
 */
export declare const ModifyPlayingSpaceRequestSchema: GenMessage<ModifyPlayingSpaceRequest>;

/**
 * @generated from message playing_spaces.v1.private.ModifyPlayingSpaceResponse
 */
export declare type ModifyPlayingSpaceResponse = Message<"playing_spaces.v1.private.ModifyPlayingSpaceResponse"> & {
  /**
   * @generated from field: playing_spaces.v1.private.PlayingSpace playingSpace = 1;
   */
  playingSpace?: PlayingSpace;
};

/**
 * Describes the message playing_spaces.v1.private.ModifyPlayingSpaceResponse.
 * Use `create(ModifyPlayingSpaceResponseSchema)` to create a new message.
 */
export declare const ModifyPlayingSpaceResponseSchema: GenMessage<ModifyPlayingSpaceResponse>;

/**
 * @generated from message playing_spaces.v1.private.ListPlayingSpacesFilter
 */
export declare type ListPlayingSpacesFilter = Message<"playing_spaces.v1.private.ListPlayingSpacesFilter"> & {
  /**
   * @generated from field: repeated string playing_space_ids = 1;
   */
  playingSpaceIds: string[];
};

/**
 * Describes the message playing_spaces.v1.private.ListPlayingSpacesFilter.
 * Use `create(ListPlayingSpacesFilterSchema)` to create a new message.
 */
export declare const ListPlayingSpacesFilterSchema: GenMessage<ListPlayingSpacesFilter>;

/**
 * @generated from message playing_spaces.v1.private.ListPlayingSpacesRequest
 */
export declare type ListPlayingSpacesRequest = Message<"playing_spaces.v1.private.ListPlayingSpacesRequest"> & {
  /**
   * @generated from field: optional string query = 1;
   */
  query?: string;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 pageSize = 3;
   */
  pageSize?: number;

  /**
   * @generated from field: optional playing_spaces.v1.private.SortDirection sortDirection = 4;
   */
  sortDirection?: SortDirection;

  /**
   * @generated from field: optional playing_spaces.v1.private.ListPlayingSpacesFilter filter = 5;
   */
  filter?: ListPlayingSpacesFilter;
};

/**
 * Describes the message playing_spaces.v1.private.ListPlayingSpacesRequest.
 * Use `create(ListPlayingSpacesRequestSchema)` to create a new message.
 */
export declare const ListPlayingSpacesRequestSchema: GenMessage<ListPlayingSpacesRequest>;

/**
 * @generated from message playing_spaces.v1.private.ListPlayingSpacesResponse
 */
export declare type ListPlayingSpacesResponse = Message<"playing_spaces.v1.private.ListPlayingSpacesResponse"> & {
  /**
   * @generated from field: repeated playing_spaces.v1.private.PlayingSpace playingSpaces = 1;
   */
  playingSpaces: PlayingSpace[];

  /**
   * @generated from field: int32 totalCount = 2;
   */
  totalCount: number;
};

/**
 * Describes the message playing_spaces.v1.private.ListPlayingSpacesResponse.
 * Use `create(ListPlayingSpacesResponseSchema)` to create a new message.
 */
export declare const ListPlayingSpacesResponseSchema: GenMessage<ListPlayingSpacesResponse>;

/**
 * @generated from enum playing_spaces.v1.private.SortDirection
 */
export enum SortDirection {
  /**
   * @generated from enum value: ASC = 0;
   */
  ASC = 0,

  /**
   * @generated from enum value: DESC = 1;
   */
  DESC = 1,
}

/**
 * Describes the enum playing_spaces.v1.private.SortDirection.
 */
export declare const SortDirectionSchema: GenEnum<SortDirection>;

/**
 * @generated from service playing_spaces.v1.private.PrivatePlayingSpacesService
 */
export declare const PrivatePlayingSpacesService: GenService<{
  /**
   * @generated from rpc playing_spaces.v1.private.PrivatePlayingSpacesService.ListPlayingSpaces
   */
  listPlayingSpaces: {
    methodKind: "unary";
    input: typeof ListPlayingSpacesRequestSchema;
    output: typeof ListPlayingSpacesResponseSchema;
  },
  /**
   * @generated from rpc playing_spaces.v1.private.PrivatePlayingSpacesService.CreatePlayingSpace
   */
  createPlayingSpace: {
    methodKind: "unary";
    input: typeof CreatePlayingSpaceRequestSchema;
    output: typeof CreatePlayingSpaceResponseSchema;
  },
  /**
   * @generated from rpc playing_spaces.v1.private.PrivatePlayingSpacesService.RemovePlayingSpaces
   */
  removePlayingSpaces: {
    methodKind: "unary";
    input: typeof RemovePlayingSpacesRequestSchema;
    output: typeof RemovePlayingSpacesResponseSchema;
  },
  /**
   * @generated from rpc playing_spaces.v1.private.PrivatePlayingSpacesService.ModifyPlayingSpace
   */
  modifyPlayingSpace: {
    methodKind: "unary";
    input: typeof ModifyPlayingSpaceRequestSchema;
    output: typeof ModifyPlayingSpaceResponseSchema;
  },
}>;

