// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file playing-spaces/v1/private/playing-spaces.proto (package playing_spaces.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum playing_spaces.v1.private.SortDirection
 */
export declare enum SortDirection {
  /**
   * @generated from enum value: ASC = 0;
   */
  ASC = 0,

  /**
   * @generated from enum value: DESC = 1;
   */
  DESC = 1,
}

/**
 * @generated from message playing_spaces.v1.private.PlayingSpace
 */
export declare class PlayingSpace extends Message<PlayingSpace> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string location_id = 2;
   */
  locationId: string;

  /**
   * @generated from field: string location_name = 3;
   */
  locationName: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  constructor(data?: PartialMessage<PlayingSpace>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.PlayingSpace";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayingSpace;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayingSpace;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayingSpace;

  static equals(a: PlayingSpace | PlainMessage<PlayingSpace> | undefined, b: PlayingSpace | PlainMessage<PlayingSpace> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.CreatePlayingSpaceRequest
 */
export declare class CreatePlayingSpaceRequest extends Message<CreatePlayingSpaceRequest> {
  /**
   * @generated from field: string location_id = 1;
   */
  locationId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  constructor(data?: PartialMessage<CreatePlayingSpaceRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.CreatePlayingSpaceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlayingSpaceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlayingSpaceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlayingSpaceRequest;

  static equals(a: CreatePlayingSpaceRequest | PlainMessage<CreatePlayingSpaceRequest> | undefined, b: CreatePlayingSpaceRequest | PlainMessage<CreatePlayingSpaceRequest> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.CreatePlayingSpaceResponse
 */
export declare class CreatePlayingSpaceResponse extends Message<CreatePlayingSpaceResponse> {
  /**
   * @generated from field: playing_spaces.v1.private.PlayingSpace playingSpace = 1;
   */
  playingSpace?: PlayingSpace;

  constructor(data?: PartialMessage<CreatePlayingSpaceResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.CreatePlayingSpaceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlayingSpaceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlayingSpaceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlayingSpaceResponse;

  static equals(a: CreatePlayingSpaceResponse | PlainMessage<CreatePlayingSpaceResponse> | undefined, b: CreatePlayingSpaceResponse | PlainMessage<CreatePlayingSpaceResponse> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.RemovePlayingSpacesRequest
 */
export declare class RemovePlayingSpacesRequest extends Message<RemovePlayingSpacesRequest> {
  /**
   * @generated from field: repeated string playingSpaceIds = 1;
   */
  playingSpaceIds: string[];

  constructor(data?: PartialMessage<RemovePlayingSpacesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.RemovePlayingSpacesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemovePlayingSpacesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemovePlayingSpacesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemovePlayingSpacesRequest;

  static equals(a: RemovePlayingSpacesRequest | PlainMessage<RemovePlayingSpacesRequest> | undefined, b: RemovePlayingSpacesRequest | PlainMessage<RemovePlayingSpacesRequest> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.RemovePlayingSpacesResponse
 */
export declare class RemovePlayingSpacesResponse extends Message<RemovePlayingSpacesResponse> {
  constructor(data?: PartialMessage<RemovePlayingSpacesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.RemovePlayingSpacesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemovePlayingSpacesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemovePlayingSpacesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemovePlayingSpacesResponse;

  static equals(a: RemovePlayingSpacesResponse | PlainMessage<RemovePlayingSpacesResponse> | undefined, b: RemovePlayingSpacesResponse | PlainMessage<RemovePlayingSpacesResponse> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.ModifyPlayingSpaceRequest
 */
export declare class ModifyPlayingSpaceRequest extends Message<ModifyPlayingSpaceRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string location_id = 3;
   */
  locationId?: string;

  constructor(data?: PartialMessage<ModifyPlayingSpaceRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.ModifyPlayingSpaceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModifyPlayingSpaceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModifyPlayingSpaceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModifyPlayingSpaceRequest;

  static equals(a: ModifyPlayingSpaceRequest | PlainMessage<ModifyPlayingSpaceRequest> | undefined, b: ModifyPlayingSpaceRequest | PlainMessage<ModifyPlayingSpaceRequest> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.ModifyPlayingSpaceResponse
 */
export declare class ModifyPlayingSpaceResponse extends Message<ModifyPlayingSpaceResponse> {
  /**
   * @generated from field: playing_spaces.v1.private.PlayingSpace playingSpace = 1;
   */
  playingSpace?: PlayingSpace;

  constructor(data?: PartialMessage<ModifyPlayingSpaceResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.ModifyPlayingSpaceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModifyPlayingSpaceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModifyPlayingSpaceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModifyPlayingSpaceResponse;

  static equals(a: ModifyPlayingSpaceResponse | PlainMessage<ModifyPlayingSpaceResponse> | undefined, b: ModifyPlayingSpaceResponse | PlainMessage<ModifyPlayingSpaceResponse> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.ListPlayingSpacesRequest
 */
export declare class ListPlayingSpacesRequest extends Message<ListPlayingSpacesRequest> {
  /**
   * @generated from field: optional string query = 1;
   */
  query?: string;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 pageSize = 3;
   */
  pageSize?: number;

  /**
   * @generated from field: optional playing_spaces.v1.private.SortDirection sortDirection = 4;
   */
  sortDirection?: SortDirection;

  constructor(data?: PartialMessage<ListPlayingSpacesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.ListPlayingSpacesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPlayingSpacesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPlayingSpacesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPlayingSpacesRequest;

  static equals(a: ListPlayingSpacesRequest | PlainMessage<ListPlayingSpacesRequest> | undefined, b: ListPlayingSpacesRequest | PlainMessage<ListPlayingSpacesRequest> | undefined): boolean;
}

/**
 * @generated from message playing_spaces.v1.private.ListPlayingSpacesResponse
 */
export declare class ListPlayingSpacesResponse extends Message<ListPlayingSpacesResponse> {
  /**
   * @generated from field: repeated playing_spaces.v1.private.PlayingSpace playingSpaces = 1;
   */
  playingSpaces: PlayingSpace[];

  /**
   * @generated from field: int32 totalCount = 2;
   */
  totalCount: number;

  constructor(data?: PartialMessage<ListPlayingSpacesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "playing_spaces.v1.private.ListPlayingSpacesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPlayingSpacesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPlayingSpacesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPlayingSpacesResponse;

  static equals(a: ListPlayingSpacesResponse | PlainMessage<ListPlayingSpacesResponse> | undefined, b: ListPlayingSpacesResponse | PlainMessage<ListPlayingSpacesResponse> | undefined): boolean;
}

