// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file playing-spaces/v1/private/playing-spaces.proto (package playingspaces.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePlayingSpaceRequest, CreatePlayingSpaceResponse, ListPlayingSpacesRequest, ListPlayingSpacesResponse, ModifyPlayingSpaceRequest, ModifyPlayingSpaceResponse, RemovePlayingSpacesRequest, RemovePlayingSpacesResponse } from "./playing-spaces_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service playingspaces.v1.private.PrivatePlayingSpacesService
 */
export declare const PrivatePlayingSpacesService: {
  readonly typeName: "playingspaces.v1.private.PrivatePlayingSpacesService",
  readonly methods: {
    /**
     * @generated from rpc playingspaces.v1.private.PrivatePlayingSpacesService.ListPlayingSpaces
     */
    readonly listPlayingSpaces: {
      readonly name: "ListPlayingSpaces",
      readonly I: typeof ListPlayingSpacesRequest,
      readonly O: typeof ListPlayingSpacesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc playingspaces.v1.private.PrivatePlayingSpacesService.CreatePlayingSpace
     */
    readonly createPlayingSpace: {
      readonly name: "CreatePlayingSpace",
      readonly I: typeof CreatePlayingSpaceRequest,
      readonly O: typeof CreatePlayingSpaceResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc playingspaces.v1.private.PrivatePlayingSpacesService.RemovePlayingSpaces
     */
    readonly removePlayingSpaces: {
      readonly name: "RemovePlayingSpaces",
      readonly I: typeof RemovePlayingSpacesRequest,
      readonly O: typeof RemovePlayingSpacesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc playingspaces.v1.private.PrivatePlayingSpacesService.ModifyPlayingSpace
     */
    readonly modifyPlayingSpace: {
      readonly name: "ModifyPlayingSpace",
      readonly I: typeof ModifyPlayingSpaceRequest,
      readonly O: typeof ModifyPlayingSpaceResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

