// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file subscriptions/v1/private/subscriptions.proto (package subscriptions.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetOrganisationPlanRequest, GetOrganisationPlanResponse } from "./subscriptions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service subscriptions.v1.private.PrivateSubscriptionsService
 */
export declare const PrivateSubscriptionsService: {
  readonly typeName: "subscriptions.v1.private.PrivateSubscriptionsService",
  readonly methods: {
    /**
     * @generated from rpc subscriptions.v1.private.PrivateSubscriptionsService.GetOrganisationPlan
     */
    readonly getOrganisationPlan: {
      readonly name: "GetOrganisationPlan",
      readonly I: typeof GetOrganisationPlanRequest,
      readonly O: typeof GetOrganisationPlanResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

