// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file subscriptions/v1/private/subscriptions.proto (package subscriptions.v1.private, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file subscriptions/v1/private/subscriptions.proto.
 */
export const file_subscriptions_v1_private_subscriptions = /*@__PURE__*/
  fileDesc("CixzdWJzY3JpcHRpb25zL3YxL3ByaXZhdGUvc3Vic2NyaXB0aW9ucy5wcm90bxIYc3Vic2NyaXB0aW9ucy52MS5wcml2YXRlImoKEFN1YnNjcmlwdGlvblBsYW4SCgoCaWQYASABKAkSGAoQc3Vic2NyaXB0aW9uX2tleRgCIAEoCRIMCgRuYW1lGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJEg0KBXByaWNlGAUgASgCIhwKGkdldE9yZ2FuaXNhdGlvblBsYW5SZXF1ZXN0IlcKG0dldE9yZ2FuaXNhdGlvblBsYW5SZXNwb25zZRI4CgRwbGFuGAEgASgLMiouc3Vic2NyaXB0aW9ucy52MS5wcml2YXRlLlN1YnNjcmlwdGlvblBsYW4ypAEKG1ByaXZhdGVTdWJzY3JpcHRpb25zU2VydmljZRKEAQoTR2V0T3JnYW5pc2F0aW9uUGxhbhI0LnN1YnNjcmlwdGlvbnMudjEucHJpdmF0ZS5HZXRPcmdhbmlzYXRpb25QbGFuUmVxdWVzdBo1LnN1YnNjcmlwdGlvbnMudjEucHJpdmF0ZS5HZXRPcmdhbmlzYXRpb25QbGFuUmVzcG9uc2UiAEJmWmRnaXRodWIuY29tL2tlZWdhbmNyYWlnY3J1aWNrc2hhbmsvdm9sbGV5LWFwaS1jb25uZWN0L3N1YnNjcmlwdGlvbnMvdjEvcHJpdmF0ZTtzdWJzY3JpcHRpb25zdjFwcml2YXRlYgZwcm90bzM");

/**
 * Describes the message subscriptions.v1.private.SubscriptionPlan.
 * Use `create(SubscriptionPlanSchema)` to create a new message.
 */
export const SubscriptionPlanSchema = /*@__PURE__*/
  messageDesc(file_subscriptions_v1_private_subscriptions, 0);

/**
 * Describes the message subscriptions.v1.private.GetOrganisationPlanRequest.
 * Use `create(GetOrganisationPlanRequestSchema)` to create a new message.
 */
export const GetOrganisationPlanRequestSchema = /*@__PURE__*/
  messageDesc(file_subscriptions_v1_private_subscriptions, 1);

/**
 * Describes the message subscriptions.v1.private.GetOrganisationPlanResponse.
 * Use `create(GetOrganisationPlanResponseSchema)` to create a new message.
 */
export const GetOrganisationPlanResponseSchema = /*@__PURE__*/
  messageDesc(file_subscriptions_v1_private_subscriptions, 2);

/**
 * @generated from service subscriptions.v1.private.PrivateSubscriptionsService
 */
export const PrivateSubscriptionsService = /*@__PURE__*/
  serviceDesc(file_subscriptions_v1_private_subscriptions, 0);

