// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file subscriptions/v1/private/subscriptions.proto (package subscriptions.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetOrganisationPlanRequest, GetOrganisationPlanResponse } from "./subscriptions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service subscriptions.v1.private.PrivateSubscriptionsService
 */
export const PrivateSubscriptionsService = {
  typeName: "subscriptions.v1.private.PrivateSubscriptionsService",
  methods: {
    /**
     * @generated from rpc subscriptions.v1.private.PrivateSubscriptionsService.GetOrganisationPlan
     */
    getOrganisationPlan: {
      name: "GetOrganisationPlan",
      I: GetOrganisationPlanRequest,
      O: GetOrganisationPlanResponse,
      kind: MethodKind.Unary,
    },
  }
};

