// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file subscriptions/v1/private/subscriptions.proto (package subscriptions.v1.private, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file subscriptions/v1/private/subscriptions.proto.
 */
export declare const file_subscriptions_v1_private_subscriptions: GenFile;

/**
 * @generated from message subscriptions.v1.private.SubscriptionPlan
 */
export declare type SubscriptionPlan = Message<"subscriptions.v1.private.SubscriptionPlan"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string subscription_key = 2;
   */
  subscriptionKey: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: float price = 5;
   */
  price: number;
};

/**
 * Describes the message subscriptions.v1.private.SubscriptionPlan.
 * Use `create(SubscriptionPlanSchema)` to create a new message.
 */
export declare const SubscriptionPlanSchema: GenMessage<SubscriptionPlan>;

/**
 * @generated from message subscriptions.v1.private.GetOrganisationPlanRequest
 */
export declare type GetOrganisationPlanRequest = Message<"subscriptions.v1.private.GetOrganisationPlanRequest"> & {
};

/**
 * Describes the message subscriptions.v1.private.GetOrganisationPlanRequest.
 * Use `create(GetOrganisationPlanRequestSchema)` to create a new message.
 */
export declare const GetOrganisationPlanRequestSchema: GenMessage<GetOrganisationPlanRequest>;

/**
 * @generated from message subscriptions.v1.private.GetOrganisationPlanResponse
 */
export declare type GetOrganisationPlanResponse = Message<"subscriptions.v1.private.GetOrganisationPlanResponse"> & {
  /**
   * @generated from field: subscriptions.v1.private.SubscriptionPlan plan = 1;
   */
  plan?: SubscriptionPlan;
};

/**
 * Describes the message subscriptions.v1.private.GetOrganisationPlanResponse.
 * Use `create(GetOrganisationPlanResponseSchema)` to create a new message.
 */
export declare const GetOrganisationPlanResponseSchema: GenMessage<GetOrganisationPlanResponse>;

/**
 * @generated from service subscriptions.v1.private.PrivateSubscriptionsService
 */
export declare const PrivateSubscriptionsService: GenService<{
  /**
   * @generated from rpc subscriptions.v1.private.PrivateSubscriptionsService.GetOrganisationPlan
   */
  getOrganisationPlan: {
    methodKind: "unary";
    input: typeof GetOrganisationPlanRequestSchema;
    output: typeof GetOrganisationPlanResponseSchema;
  },
}>;

