// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file users/v1/private/users.proto (package users.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message users.v1.private.MeRequest
 */
export const MeRequest = proto3.makeMessageType(
  "users.v1.private.MeRequest",
  [],
);

/**
 * @generated from message users.v1.private.MeResponse
 */
export const MeResponse = proto3.makeMessageType(
  "users.v1.private.MeResponse",
  () => [
    { no: 1, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

