// @generated by protoc-gen-es v1.5.0 with parameter "target=js+dts"
// @generated from file users/v1/private/users.proto (package users.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message users.v1.private.User
 */
export const User = proto3.makeMessageType(
  "users.v1.private.User",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "org_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "last_logout", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "created_at", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "updated_at", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "default_org", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "active_org", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "active_org_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "verified", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message users.v1.private.Organisation
 */
export const Organisation = proto3.makeMessageType(
  "users.v1.private.Organisation",
  () => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.private.ApiToken
 */
export const ApiToken = proto3.makeMessageType(
  "users.v1.private.ApiToken",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "last_modified", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message users.v1.private.SetDefaultOrgRequest
 */
export const SetDefaultOrgRequest = proto3.makeMessageType(
  "users.v1.private.SetDefaultOrgRequest",
  () => [
    { no: 1, name: "default_org", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.private.SetDefaultOrgResponse
 */
export const SetDefaultOrgResponse = proto3.makeMessageType(
  "users.v1.private.SetDefaultOrgResponse",
  [],
);

/**
 * @generated from message users.v1.private.GetMeRequest
 */
export const GetMeRequest = proto3.makeMessageType(
  "users.v1.private.GetMeRequest",
  [],
);

/**
 * @generated from message users.v1.private.GetMeResponse
 */
export const GetMeResponse = proto3.makeMessageType(
  "users.v1.private.GetMeResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
  ],
);

/**
 * @generated from message users.v1.private.LogoutRequest
 */
export const LogoutRequest = proto3.makeMessageType(
  "users.v1.private.LogoutRequest",
  [],
);

/**
 * @generated from message users.v1.private.LogoutResponse
 */
export const LogoutResponse = proto3.makeMessageType(
  "users.v1.private.LogoutResponse",
  [],
);

/**
 * @generated from message users.v1.private.SetActiveOrgRequest
 */
export const SetActiveOrgRequest = proto3.makeMessageType(
  "users.v1.private.SetActiveOrgRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.private.SetActiveOrgResponse
 */
export const SetActiveOrgResponse = proto3.makeMessageType(
  "users.v1.private.SetActiveOrgResponse",
  [],
);

/**
 * @generated from message users.v1.private.ResendVerificationRequest
 */
export const ResendVerificationRequest = proto3.makeMessageType(
  "users.v1.private.ResendVerificationRequest",
  [],
);

/**
 * @generated from message users.v1.private.ResendVerificationResponse
 */
export const ResendVerificationResponse = proto3.makeMessageType(
  "users.v1.private.ResendVerificationResponse",
  [],
);

/**
 * @generated from message users.v1.private.CreateApiTokenRequest
 */
export const CreateApiTokenRequest = proto3.makeMessageType(
  "users.v1.private.CreateApiTokenRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.private.CreateApiTokenResponse
 */
export const CreateApiTokenResponse = proto3.makeMessageType(
  "users.v1.private.CreateApiTokenResponse",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.private.ListApiTokensRequest
 */
export const ListApiTokensRequest = proto3.makeMessageType(
  "users.v1.private.ListApiTokensRequest",
  [],
);

/**
 * @generated from message users.v1.private.ListApiTokensResponse
 */
export const ListApiTokensResponse = proto3.makeMessageType(
  "users.v1.private.ListApiTokensResponse",
  () => [
    { no: 1, name: "tokens", kind: "message", T: ApiToken, repeated: true },
  ],
);

/**
 * @generated from message users.v1.private.RemoveApiTokenRequest
 */
export const RemoveApiTokenRequest = proto3.makeMessageType(
  "users.v1.private.RemoveApiTokenRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.private.RemoveApiTokenResponse
 */
export const RemoveApiTokenResponse = proto3.makeMessageType(
  "users.v1.private.RemoveApiTokenResponse",
  [],
);

/**
 * @generated from message users.v1.private.ListOrganisationsRequest
 */
export const ListOrganisationsRequest = proto3.makeMessageType(
  "users.v1.private.ListOrganisationsRequest",
  [],
);

/**
 * @generated from message users.v1.private.ListOrganisationsResponse
 */
export const ListOrganisationsResponse = proto3.makeMessageType(
  "users.v1.private.ListOrganisationsResponse",
  () => [
    { no: 1, name: "organisations", kind: "message", T: Organisation, repeated: true },
  ],
);

/**
 * @generated from message users.v1.private.CreateNewOrganisationRequest
 */
export const CreateNewOrganisationRequest = proto3.makeMessageType(
  "users.v1.private.CreateNewOrganisationRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.private.CreateNewOrganisationResponse
 */
export const CreateNewOrganisationResponse = proto3.makeMessageType(
  "users.v1.private.CreateNewOrganisationResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

