// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file players/v1/private/players.proto (package players.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddPlayerExclusionRequest, AddPlayerExclusionResponse, CreatePlayerRequest, CreatePlayerResponse, GetPlayerRequest, GetPlayerResponse, ListPlayersRequest, ListPlayersResponse, ModifyPlayerRequest, ModifyPlayerResponse, RemovePlayerExclusionRequest, RemovePlayerExclusionResponse, RemovePlayersRequest, RemovePlayersResponse } from "./players_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service players.v1.private.PrivatePlayersService
 */
export const PrivatePlayersService = {
  typeName: "players.v1.private.PrivatePlayersService",
  methods: {
    /**
     * @generated from rpc players.v1.private.PrivatePlayersService.CreatePlayer
     */
    createPlayer: {
      name: "CreatePlayer",
      I: CreatePlayerRequest,
      O: CreatePlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc players.v1.private.PrivatePlayersService.RemovePlayers
     */
    removePlayers: {
      name: "RemovePlayers",
      I: RemovePlayersRequest,
      O: RemovePlayersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc players.v1.private.PrivatePlayersService.ModifyPlayer
     */
    modifyPlayer: {
      name: "ModifyPlayer",
      I: ModifyPlayerRequest,
      O: ModifyPlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc players.v1.private.PrivatePlayersService.ListPlayers
     */
    listPlayers: {
      name: "ListPlayers",
      I: ListPlayersRequest,
      O: ListPlayersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc players.v1.private.PrivatePlayersService.GetPlayer
     */
    getPlayer: {
      name: "GetPlayer",
      I: GetPlayerRequest,
      O: GetPlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc players.v1.private.PrivatePlayersService.AddPlayerExclusion
     */
    addPlayerExclusion: {
      name: "AddPlayerExclusion",
      I: AddPlayerExclusionRequest,
      O: AddPlayerExclusionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc players.v1.private.PrivatePlayersService.RemovePlayerExclusion
     */
    removePlayerExclusion: {
      name: "RemovePlayerExclusion",
      I: RemovePlayerExclusionRequest,
      O: RemovePlayerExclusionResponse,
      kind: MethodKind.Unary,
    },
  }
};

