// @generated by protoc-gen-connect-query v1.4.1 with parameter "target=js+dts"
// @generated from file players/v1/private/players.proto (package players.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddPlayerExclusionRequest, AddPlayerExclusionResponse, CreatePlayerRequest, CreatePlayerResponse, GetPlayerRequest, GetPlayerResponse, ListPlayersRequest, ListPlayersResponse, ModifyPlayerRequest, ModifyPlayerResponse, RemovePlayerExclusionRequest, RemovePlayerExclusionResponse, RemovePlayersRequest, RemovePlayersResponse } from "./players_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc players.v1.private.PrivatePlayersService.CreatePlayer
 */
export const createPlayer: {
      readonly name: "CreatePlayer",
      readonly I: typeof CreatePlayerRequest,
      readonly O: typeof CreatePlayerResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "players.v1.private.PrivatePlayersService"
  }
};
/**
 * @generated from rpc players.v1.private.PrivatePlayersService.RemovePlayers
 */
export const removePlayers: {
      readonly name: "RemovePlayers",
      readonly I: typeof RemovePlayersRequest,
      readonly O: typeof RemovePlayersResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "players.v1.private.PrivatePlayersService"
  }
};
/**
 * @generated from rpc players.v1.private.PrivatePlayersService.ModifyPlayer
 */
export const modifyPlayer: {
      readonly name: "ModifyPlayer",
      readonly I: typeof ModifyPlayerRequest,
      readonly O: typeof ModifyPlayerResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "players.v1.private.PrivatePlayersService"
  }
};
/**
 * @generated from rpc players.v1.private.PrivatePlayersService.ListPlayers
 */
export const listPlayers: {
      readonly name: "ListPlayers",
      readonly I: typeof ListPlayersRequest,
      readonly O: typeof ListPlayersResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "players.v1.private.PrivatePlayersService"
  }
};
/**
 * @generated from rpc players.v1.private.PrivatePlayersService.GetPlayer
 */
export const getPlayer: {
      readonly name: "GetPlayer",
      readonly I: typeof GetPlayerRequest,
      readonly O: typeof GetPlayerResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "players.v1.private.PrivatePlayersService"
  }
};
/**
 * @generated from rpc players.v1.private.PrivatePlayersService.AddPlayerExclusion
 */
export const addPlayerExclusion: {
      readonly name: "AddPlayerExclusion",
      readonly I: typeof AddPlayerExclusionRequest,
      readonly O: typeof AddPlayerExclusionResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "players.v1.private.PrivatePlayersService"
  }
};
/**
 * @generated from rpc players.v1.private.PrivatePlayersService.RemovePlayerExclusion
 */
export const removePlayerExclusion: {
      readonly name: "RemovePlayerExclusion",
      readonly I: typeof RemovePlayerExclusionRequest,
      readonly O: typeof RemovePlayerExclusionResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "players.v1.private.PrivatePlayersService"
  }
};
