// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file common/common.proto (package common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message common.v1.VolleyError
 */
export declare class VolleyError extends Message<VolleyError> {
  /**
   * @generated from field: string display_message = 1;
   */
  displayMessage: string;

  /**
   * @generated from field: string internal_message = 2;
   */
  internalMessage: string;

  /**
   * @generated from field: int32 status_code = 3;
   */
  statusCode: number;

  /**
   * @generated from field: map<string, string> metadata = 5;
   */
  metadata: { [key: string]: string };

  constructor(data?: PartialMessage<VolleyError>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "common.v1.VolleyError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VolleyError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VolleyError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VolleyError;

  static equals(a: VolleyError | PlainMessage<VolleyError> | undefined, b: VolleyError | PlainMessage<VolleyError> | undefined): boolean;
}

