// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file common/common.proto (package common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message common.v1.VolleyError
 */
export const VolleyError = /*@__PURE__*/ proto3.makeMessageType(
  "common.v1.VolleyError",
  () => [
    { no: 1, name: "display_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "internal_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "metadata", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
);

