// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file common/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/common.proto.
 */
export const file_common_common = /*@__PURE__*/
  fileDesc("ChNjb21tb24vY29tbW9uLnByb3RvEgljb21tb24udjEivgEKC1ZvbGxleUVycm9yEhcKD2Rpc3BsYXlfbWVzc2FnZRgBIAEoCRIYChBpbnRlcm5hbF9tZXNzYWdlGAIgASgJEhMKC3N0YXR1c19jb2RlGAMgASgFEjYKCG1ldGFkYXRhGAUgAygLMiQuY29tbW9uLnYxLlZvbGxleUVycm9yLk1ldGFkYXRhRW50cnkaLwoNTWV0YWRhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQklaR2dpdGh1Yi5jb20va2VlZ2FuY3JhaWdjcnVpY2tzaGFuay92b2xsZXktYXBpLWNvbm5lY3QvY29tbW9uLnYxO2NvbW1vbnYxYgZwcm90bzM");

/**
 * Describes the message common.v1.VolleyError.
 * Use `create(VolleyErrorSchema)` to create a new message.
 */
export const VolleyErrorSchema = /*@__PURE__*/
  messageDesc(file_common_common, 0);

