// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file draw/v1/private/draw.proto (package draw.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateDrawRequest, CreateDrawResponse, DeleteDrawRequest, DeleteDrawResponse, GetDrawRequest, GetDrawResponse, GetDrawRoundRequest, GetDrawRoundResponse, UpdateDrawRequest, UpdateDrawResponse } from "./draw_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service draw.v1.private.DrawService
 */
export const DrawService = {
  typeName: "draw.v1.private.DrawService",
  methods: {
    /**
     * @generated from rpc draw.v1.private.DrawService.CreateDraw
     */
    createDraw: {
      name: "CreateDraw",
      I: CreateDrawRequest,
      O: CreateDrawResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc draw.v1.private.DrawService.GetDraw
     */
    getDraw: {
      name: "GetDraw",
      I: GetDrawRequest,
      O: GetDrawResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc draw.v1.private.DrawService.UpdateDraw
     */
    updateDraw: {
      name: "UpdateDraw",
      I: UpdateDrawRequest,
      O: UpdateDrawResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc draw.v1.private.DrawService.DeleteDraw
     */
    deleteDraw: {
      name: "DeleteDraw",
      I: DeleteDrawRequest,
      O: DeleteDrawResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc draw.v1.private.DrawService.GetDrawRound
     */
    getDrawRound: {
      name: "GetDrawRound",
      I: GetDrawRoundRequest,
      O: GetDrawRoundResponse,
      kind: MethodKind.Unary,
    },
  }
};

