// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file draw/v1/private/draw.proto (package draws.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateDrawRequest, CreateDrawResponse} from "./draw_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service draws.v1.private.PrivateDrawsService
 */
export const PrivateDrawsService = {
  typeName: "draws.v1.private.PrivateDrawsService",
  methods: {
    /**
     * @generated from rpc draws.v1.private.PrivateDrawsService.CreateDraw
     */
    createDraw: {
      name: "CreateDraw",
      I: CreateDrawRequest,
      O: CreateDrawResponse,
      kind: MethodKind.Unary,
    },
  }
};

