// @generated by protoc-gen-connect-query v1.4.0 with parameter "target=js+dts"
// @generated from file draw/v1/private/draw.proto (package draw.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateFlexibleRoundRobinDrawRequest, CreateFlexibleRoundRobinDrawResponse, DeleteDrawRequest, DeleteDrawResponse, GetDrawRequest, GetDrawResponse, GetFlexibleRoundRobinDrawRoundRequest, GetFlexibleRoundRobinDrawRoundResponse, UpdateFlexibleRoundRobinDrawRequest, UpdateFlexibleRoundRobinDrawResponse } from "./draw_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc draw.v1.private.PrivateDrawService.GetDraw
 */
export const getDraw: {
      readonly name: "GetDraw",
      readonly I: typeof GetDrawRequest,
      readonly O: typeof GetDrawResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "draw.v1.private.PrivateDrawService"
  }
};
/**
 * @generated from rpc draw.v1.private.PrivateDrawService.DeleteDraw
 */
export const deleteDraw: {
      readonly name: "DeleteDraw",
      readonly I: typeof DeleteDrawRequest,
      readonly O: typeof DeleteDrawResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "draw.v1.private.PrivateDrawService"
  }
};
/**
 * @generated from rpc draw.v1.private.PrivateDrawService.CreateFlexibleRoundRobinDraw
 */
export const createFlexibleRoundRobinDraw: {
      readonly name: "CreateFlexibleRoundRobinDraw",
      readonly I: typeof CreateFlexibleRoundRobinDrawRequest,
      readonly O: typeof CreateFlexibleRoundRobinDrawResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "draw.v1.private.PrivateDrawService"
  }
};
/**
 * @generated from rpc draw.v1.private.PrivateDrawService.UpdateFlexibleRoundRobinDraw
 */
export const updateFlexibleRoundRobinDraw: {
      readonly name: "UpdateFlexibleRoundRobinDraw",
      readonly I: typeof UpdateFlexibleRoundRobinDrawRequest,
      readonly O: typeof UpdateFlexibleRoundRobinDrawResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "draw.v1.private.PrivateDrawService"
  }
};
/**
 * @generated from rpc draw.v1.private.PrivateDrawService.GetFlexibleRoundRobinDrawRound
 */
export const getFlexibleRoundRobinDrawRound: {
      readonly name: "GetFlexibleRoundRobinDrawRound",
      readonly I: typeof GetFlexibleRoundRobinDrawRoundRequest,
      readonly O: typeof GetFlexibleRoundRobinDrawRoundResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "draw.v1.private.PrivateDrawService"
  }
};
