// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=js+dts"
// @generated from file users/v1/public/users.proto (package users.v1.public, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTokenRequest, GetTokenResponse } from "./users_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc users.v1.public.PublicUsersService.GetToken
 */
export const getToken: {
      readonly name: "GetToken",
      readonly I: typeof GetTokenRequest,
      readonly O: typeof GetTokenResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "users.v1.public.PublicUsersService"
  }
};
