// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file users/v1/public/users.proto (package users.v1.public, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTokenRequest, GetTokenResponse } from "./users_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service users.v1.public.PublicUsersService
 */
export declare const PublicUsersService: {
  readonly typeName: "users.v1.public.PublicUsersService",
  readonly methods: {
    /**
     * @generated from rpc users.v1.public.PublicUsersService.GetToken
     */
    readonly getToken: {
      readonly name: "GetToken",
      readonly I: typeof GetTokenRequest,
      readonly O: typeof GetTokenResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

