// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file users/v1/public/users.proto (package users.v1.public, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {LoginUserRequest, LoginUserResponse, RegisterUserRequest, RegisterUserResponse} from "./users_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service users.v1.public.PublicUsersService
 */
export declare const PublicUsersService: {
  readonly typeName: "users.v1.public.PublicUsersService",
  readonly methods: {
    /**
     * @generated from rpc users.v1.public.PublicUsersService.RegisterUser
     */
    readonly registerUser: {
      readonly name: "RegisterUser",
      readonly I: typeof RegisterUserRequest,
      readonly O: typeof RegisterUserResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.v1.public.PublicUsersService.LoginUser
     */
    readonly loginUser: {
      readonly name: "LoginUser",
      readonly I: typeof LoginUserRequest,
      readonly O: typeof LoginUserResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

