// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file locations/v1/private/locations.proto (package locations.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {AddLocationRequest, AddLocationResponse, ModifyLocationRequest, ModifyLocationResponse} from "./locations_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service locations.v1.private.PublicUsersService
 */
export declare const PublicUsersService: {
  readonly typeName: "locations.v1.private.PublicUsersService",
  readonly methods: {
    /**
     * @generated from rpc locations.v1.private.PublicUsersService.AddLocation
     */
    readonly addLocation: {
      readonly name: "AddLocation",
      readonly I: typeof AddLocationRequest,
      readonly O: typeof AddLocationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc locations.v1.private.PublicUsersService.ModifyLocation
     */
    readonly modifyLocation: {
      readonly name: "ModifyLocation",
      readonly I: typeof ModifyLocationRequest,
      readonly O: typeof ModifyLocationResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

