// @generated by protoc-gen-connect-query v1.4.1 with parameter "target=js+dts"
// @generated from file locations/v1/private/locations.proto (package locations.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddLocationRequest, AddLocationResponse, ListLocationsRequest, ListLocationsResponse, ModifyLocationRequest, ModifyLocationResponse, RemoveLocationsRequest, RemoveLocationsResponse } from "./locations_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc locations.v1.private.PrivateLocationsService.AddLocation
 */
export const addLocation: {
      readonly name: "AddLocation",
      readonly I: typeof AddLocationRequest,
      readonly O: typeof AddLocationResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "locations.v1.private.PrivateLocationsService"
  }
};
/**
 * @generated from rpc locations.v1.private.PrivateLocationsService.ModifyLocation
 */
export const modifyLocation: {
      readonly name: "ModifyLocation",
      readonly I: typeof ModifyLocationRequest,
      readonly O: typeof ModifyLocationResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "locations.v1.private.PrivateLocationsService"
  }
};
/**
 * @generated from rpc locations.v1.private.PrivateLocationsService.ListLocations
 */
export const listLocations: {
      readonly name: "ListLocations",
      readonly I: typeof ListLocationsRequest,
      readonly O: typeof ListLocationsResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "locations.v1.private.PrivateLocationsService"
  }
};
/**
 * @generated from rpc locations.v1.private.PrivateLocationsService.RemoveLocations
 */
export const removeLocations: {
      readonly name: "RemoveLocations",
      readonly I: typeof RemoveLocationsRequest,
      readonly O: typeof RemoveLocationsResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "locations.v1.private.PrivateLocationsService"
  }
};
