// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file locations/v1/private/locations.proto (package locations.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message locations.v1.private.AddLocationRequest
 */
export const AddLocationRequest = proto3.makeMessageType(
  "locations.v1.private.AddLocationRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message locations.v1.private.AddLocationResponse
 */
export const AddLocationResponse = proto3.makeMessageType(
  "locations.v1.private.AddLocationResponse",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message locations.v1.private.ModifyLocationRequest
 */
export const ModifyLocationRequest = proto3.makeMessageType(
  "locations.v1.private.ModifyLocationRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message locations.v1.private.ModifyLocationResponse
 */
export const ModifyLocationResponse = proto3.makeMessageType(
  "locations.v1.private.ModifyLocationResponse",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

