// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file locations/v1/private/locations.proto (package locations.v1.private, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file locations/v1/private/locations.proto.
 */
export const file_locations_v1_private_locations = /*@__PURE__*/
  fileDesc("CiRsb2NhdGlvbnMvdjEvcHJpdmF0ZS9sb2NhdGlvbnMucHJvdG8SFGxvY2F0aW9ucy52MS5wcml2YXRlIigKDFNpdGVMb2NhdGlvbhIMCgRuYW1lGAEgASgJEgoKAmlkGAIgASgJIi0KFlJlbW92ZUxvY2F0aW9uc1JlcXVlc3QSEwoLbG9jYXRpb25JZHMYASADKAkiGQoXUmVtb3ZlTG9jYXRpb25zUmVzcG9uc2UiIgoSQWRkTG9jYXRpb25SZXF1ZXN0EgwKBG5hbWUYASABKAkiLwoTQWRkTG9jYXRpb25SZXNwb25zZRIMCgRuYW1lGAEgASgJEgoKAmlkGAIgASgJIscBChRMaXN0TG9jYXRpb25zUmVxdWVzdBISCgVxdWVyeRgBIAEoCUgAiAEBEhEKBHBhZ2UYAiABKAVIAYgBARIVCghwYWdlU2l6ZRgDIAEoBUgCiAEBEj8KDXNvcnREaXJlY3Rpb24YBCABKA4yIy5sb2NhdGlvbnMudjEucHJpdmF0ZS5Tb3J0RGlyZWN0aW9uSAOIAQFCCAoGX3F1ZXJ5QgcKBV9wYWdlQgsKCV9wYWdlU2l6ZUIQCg5fc29ydERpcmVjdGlvbiJiChVMaXN0TG9jYXRpb25zUmVzcG9uc2USNQoJbG9jYXRpb25zGAEgAygLMiIubG9jYXRpb25zLnYxLnByaXZhdGUuU2l0ZUxvY2F0aW9uEhIKCnRvdGFsQ291bnQYAiABKAUiMQoVTW9kaWZ5TG9jYXRpb25SZXF1ZXN0EgwKBG5hbWUYASABKAkSCgoCaWQYAiABKAkiMgoWTW9kaWZ5TG9jYXRpb25SZXNwb25zZRIMCgRuYW1lGAEgASgJEgoKAmlkGAIgASgJKiIKDVNvcnREaXJlY3Rpb24SBwoDQVNDEAASCAoEREVTQxABMswDChdQcml2YXRlTG9jYXRpb25zU2VydmljZRJkCgtBZGRMb2NhdGlvbhIoLmxvY2F0aW9ucy52MS5wcml2YXRlLkFkZExvY2F0aW9uUmVxdWVzdBopLmxvY2F0aW9ucy52MS5wcml2YXRlLkFkZExvY2F0aW9uUmVzcG9uc2UiABJtCg5Nb2RpZnlMb2NhdGlvbhIrLmxvY2F0aW9ucy52MS5wcml2YXRlLk1vZGlmeUxvY2F0aW9uUmVxdWVzdBosLmxvY2F0aW9ucy52MS5wcml2YXRlLk1vZGlmeUxvY2F0aW9uUmVzcG9uc2UiABJqCg1MaXN0TG9jYXRpb25zEioubG9jYXRpb25zLnYxLnByaXZhdGUuTGlzdExvY2F0aW9uc1JlcXVlc3QaKy5sb2NhdGlvbnMudjEucHJpdmF0ZS5MaXN0TG9jYXRpb25zUmVzcG9uc2UiABJwCg9SZW1vdmVMb2NhdGlvbnMSLC5sb2NhdGlvbnMudjEucHJpdmF0ZS5SZW1vdmVMb2NhdGlvbnNSZXF1ZXN0Gi0ubG9jYXRpb25zLnYxLnByaXZhdGUuUmVtb3ZlTG9jYXRpb25zUmVzcG9uc2UiAEJeWlxnaXRodWIuY29tL2tlZWdhbmNyYWlnY3J1aWNrc2hhbmsvdm9sbGV5LWFwaS1jb25uZWN0L2xvY2F0aW9ucy92MS9wcml2YXRlO2xvY2F0aW9uc3YxcHJpdmF0ZWIGcHJvdG8z");

/**
 * Describes the message locations.v1.private.SiteLocation.
 * Use `create(SiteLocationSchema)` to create a new message.
 */
export const SiteLocationSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 0);

/**
 * Describes the message locations.v1.private.RemoveLocationsRequest.
 * Use `create(RemoveLocationsRequestSchema)` to create a new message.
 */
export const RemoveLocationsRequestSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 1);

/**
 * Describes the message locations.v1.private.RemoveLocationsResponse.
 * Use `create(RemoveLocationsResponseSchema)` to create a new message.
 */
export const RemoveLocationsResponseSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 2);

/**
 * Describes the message locations.v1.private.AddLocationRequest.
 * Use `create(AddLocationRequestSchema)` to create a new message.
 */
export const AddLocationRequestSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 3);

/**
 * Describes the message locations.v1.private.AddLocationResponse.
 * Use `create(AddLocationResponseSchema)` to create a new message.
 */
export const AddLocationResponseSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 4);

/**
 * Describes the message locations.v1.private.ListLocationsRequest.
 * Use `create(ListLocationsRequestSchema)` to create a new message.
 */
export const ListLocationsRequestSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 5);

/**
 * Describes the message locations.v1.private.ListLocationsResponse.
 * Use `create(ListLocationsResponseSchema)` to create a new message.
 */
export const ListLocationsResponseSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 6);

/**
 * Describes the message locations.v1.private.ModifyLocationRequest.
 * Use `create(ModifyLocationRequestSchema)` to create a new message.
 */
export const ModifyLocationRequestSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 7);

/**
 * Describes the message locations.v1.private.ModifyLocationResponse.
 * Use `create(ModifyLocationResponseSchema)` to create a new message.
 */
export const ModifyLocationResponseSchema = /*@__PURE__*/
  messageDesc(file_locations_v1_private_locations, 8);

/**
 * Describes the enum locations.v1.private.SortDirection.
 */
export const SortDirectionSchema = /*@__PURE__*/
  enumDesc(file_locations_v1_private_locations, 0);

/**
 * @generated from enum locations.v1.private.SortDirection
 */
export const SortDirection = /*@__PURE__*/
  tsEnum(SortDirectionSchema);

/**
 * @generated from service locations.v1.private.PrivateLocationsService
 */
export const PrivateLocationsService = /*@__PURE__*/
  serviceDesc(file_locations_v1_private_locations, 0);

