// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts"
// @generated from file locations/v1/private/locations.proto (package locations.v1.private, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file locations/v1/private/locations.proto.
 */
export declare const file_locations_v1_private_locations: GenFile;

/**
 * @generated from message locations.v1.private.SiteLocation
 */
export declare type SiteLocation = Message<"locations.v1.private.SiteLocation"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message locations.v1.private.SiteLocation.
 * Use `create(SiteLocationSchema)` to create a new message.
 */
export declare const SiteLocationSchema: GenMessage<SiteLocation>;

/**
 * @generated from message locations.v1.private.RemoveLocationsRequest
 */
export declare type RemoveLocationsRequest = Message<"locations.v1.private.RemoveLocationsRequest"> & {
  /**
   * @generated from field: repeated string locationIds = 1;
   */
  locationIds: string[];
};

/**
 * Describes the message locations.v1.private.RemoveLocationsRequest.
 * Use `create(RemoveLocationsRequestSchema)` to create a new message.
 */
export declare const RemoveLocationsRequestSchema: GenMessage<RemoveLocationsRequest>;

/**
 * @generated from message locations.v1.private.RemoveLocationsResponse
 */
export declare type RemoveLocationsResponse = Message<"locations.v1.private.RemoveLocationsResponse"> & {
};

/**
 * Describes the message locations.v1.private.RemoveLocationsResponse.
 * Use `create(RemoveLocationsResponseSchema)` to create a new message.
 */
export declare const RemoveLocationsResponseSchema: GenMessage<RemoveLocationsResponse>;

/**
 * @generated from message locations.v1.private.AddLocationRequest
 */
export declare type AddLocationRequest = Message<"locations.v1.private.AddLocationRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message locations.v1.private.AddLocationRequest.
 * Use `create(AddLocationRequestSchema)` to create a new message.
 */
export declare const AddLocationRequestSchema: GenMessage<AddLocationRequest>;

/**
 * @generated from message locations.v1.private.AddLocationResponse
 */
export declare type AddLocationResponse = Message<"locations.v1.private.AddLocationResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message locations.v1.private.AddLocationResponse.
 * Use `create(AddLocationResponseSchema)` to create a new message.
 */
export declare const AddLocationResponseSchema: GenMessage<AddLocationResponse>;

/**
 * @generated from message locations.v1.private.ListLocationsRequest
 */
export declare type ListLocationsRequest = Message<"locations.v1.private.ListLocationsRequest"> & {
  /**
   * @generated from field: optional string query = 1;
   */
  query?: string;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 pageSize = 3;
   */
  pageSize?: number;

  /**
   * @generated from field: optional locations.v1.private.SortDirection sortDirection = 4;
   */
  sortDirection?: SortDirection;
};

/**
 * Describes the message locations.v1.private.ListLocationsRequest.
 * Use `create(ListLocationsRequestSchema)` to create a new message.
 */
export declare const ListLocationsRequestSchema: GenMessage<ListLocationsRequest>;

/**
 * @generated from message locations.v1.private.ListLocationsResponse
 */
export declare type ListLocationsResponse = Message<"locations.v1.private.ListLocationsResponse"> & {
  /**
   * @generated from field: repeated locations.v1.private.SiteLocation locations = 1;
   */
  locations: SiteLocation[];

  /**
   * @generated from field: int32 totalCount = 2;
   */
  totalCount: number;
};

/**
 * Describes the message locations.v1.private.ListLocationsResponse.
 * Use `create(ListLocationsResponseSchema)` to create a new message.
 */
export declare const ListLocationsResponseSchema: GenMessage<ListLocationsResponse>;

/**
 * @generated from message locations.v1.private.ModifyLocationRequest
 */
export declare type ModifyLocationRequest = Message<"locations.v1.private.ModifyLocationRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message locations.v1.private.ModifyLocationRequest.
 * Use `create(ModifyLocationRequestSchema)` to create a new message.
 */
export declare const ModifyLocationRequestSchema: GenMessage<ModifyLocationRequest>;

/**
 * @generated from message locations.v1.private.ModifyLocationResponse
 */
export declare type ModifyLocationResponse = Message<"locations.v1.private.ModifyLocationResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message locations.v1.private.ModifyLocationResponse.
 * Use `create(ModifyLocationResponseSchema)` to create a new message.
 */
export declare const ModifyLocationResponseSchema: GenMessage<ModifyLocationResponse>;

/**
 * @generated from enum locations.v1.private.SortDirection
 */
export enum SortDirection {
  /**
   * @generated from enum value: ASC = 0;
   */
  ASC = 0,

  /**
   * @generated from enum value: DESC = 1;
   */
  DESC = 1,
}

/**
 * Describes the enum locations.v1.private.SortDirection.
 */
export declare const SortDirectionSchema: GenEnum<SortDirection>;

/**
 * @generated from service locations.v1.private.PrivateLocationsService
 */
export declare const PrivateLocationsService: GenService<{
  /**
   * @generated from rpc locations.v1.private.PrivateLocationsService.AddLocation
   */
  addLocation: {
    methodKind: "unary";
    input: typeof AddLocationRequestSchema;
    output: typeof AddLocationResponseSchema;
  },
  /**
   * @generated from rpc locations.v1.private.PrivateLocationsService.ModifyLocation
   */
  modifyLocation: {
    methodKind: "unary";
    input: typeof ModifyLocationRequestSchema;
    output: typeof ModifyLocationResponseSchema;
  },
  /**
   * @generated from rpc locations.v1.private.PrivateLocationsService.ListLocations
   */
  listLocations: {
    methodKind: "unary";
    input: typeof ListLocationsRequestSchema;
    output: typeof ListLocationsResponseSchema;
  },
  /**
   * @generated from rpc locations.v1.private.PrivateLocationsService.RemoveLocations
   */
  removeLocations: {
    methodKind: "unary";
    input: typeof RemoveLocationsRequestSchema;
    output: typeof RemoveLocationsResponseSchema;
  },
}>;

