// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=js+dts"
// @generated from file locations/v1/private/locations.proto (package locations.v1.private, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddLocationRequest, AddLocationResponse, ListLocationsRequest, ListLocationsResponse, ModifyLocationRequest, ModifyLocationResponse, RemoveLocationsRequest, RemoveLocationsResponse } from "./locations_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service locations.v1.private.PrivateLocationsService
 */
export declare const PrivateLocationsService: {
  readonly typeName: "locations.v1.private.PrivateLocationsService",
  readonly methods: {
    /**
     * @generated from rpc locations.v1.private.PrivateLocationsService.AddLocation
     */
    readonly addLocation: {
      readonly name: "AddLocation",
      readonly I: typeof AddLocationRequest,
      readonly O: typeof AddLocationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc locations.v1.private.PrivateLocationsService.ModifyLocation
     */
    readonly modifyLocation: {
      readonly name: "ModifyLocation",
      readonly I: typeof ModifyLocationRequest,
      readonly O: typeof ModifyLocationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc locations.v1.private.PrivateLocationsService.ListLocations
     */
    readonly listLocations: {
      readonly name: "ListLocations",
      readonly I: typeof ListLocationsRequest,
      readonly O: typeof ListLocationsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc locations.v1.private.PrivateLocationsService.RemoveLocations
     */
    readonly removeLocations: {
      readonly name: "RemoveLocations",
      readonly I: typeof RemoveLocationsRequest,
      readonly O: typeof RemoveLocationsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

