// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file court/v1/private/court.proto (package court.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";

/**
 * @generated from message court.v1.private.Court
 */
export declare class Court extends Message<Court> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string court_id = 3;
   */
  courtId: string;

  constructor(data?: PartialMessage<Court>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "court.v1.private.Court";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Court;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Court;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Court;

  static equals(a: Court | PlainMessage<Court> | undefined, b: Court | PlainMessage<Court> | undefined): boolean;
}

/**
 * @generated from message court.v1.private.CreateCourtRequest
 */
export declare class CreateCourtRequest extends Message<CreateCourtRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<CreateCourtRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "court.v1.private.CreateCourtRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCourtRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCourtRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCourtRequest;

  static equals(a: CreateCourtRequest | PlainMessage<CreateCourtRequest> | undefined, b: CreateCourtRequest | PlainMessage<CreateCourtRequest> | undefined): boolean;
}

/**
 * @generated from message court.v1.private.CreateCourtResponse
 */
export declare class CreateCourtResponse extends Message<CreateCourtResponse> {
  /**
   * @generated from field: court.v1.private.Court court = 1;
   */
  court?: Court;

  constructor(data?: PartialMessage<CreateCourtResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "court.v1.private.CreateCourtResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCourtResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCourtResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCourtResponse;

  static equals(a: CreateCourtResponse | PlainMessage<CreateCourtResponse> | undefined, b: CreateCourtResponse | PlainMessage<CreateCourtResponse> | undefined): boolean;
}

/**
 * @generated from message court.v1.private.ListCourtsRequest
 */
export declare class ListCourtsRequest extends Message<ListCourtsRequest> {
  constructor(data?: PartialMessage<ListCourtsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "court.v1.private.ListCourtsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCourtsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCourtsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCourtsRequest;

  static equals(a: ListCourtsRequest | PlainMessage<ListCourtsRequest> | undefined, b: ListCourtsRequest | PlainMessage<ListCourtsRequest> | undefined): boolean;
}

/**
 * @generated from message court.v1.private.ListCourtsResponse
 */
export declare class ListCourtsResponse extends Message<ListCourtsResponse> {
  /**
   * @generated from field: repeated court.v1.private.Court courts = 1;
   */
  courts: Court[];

  constructor(data?: PartialMessage<ListCourtsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "court.v1.private.ListCourtsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCourtsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCourtsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCourtsResponse;

  static equals(a: ListCourtsResponse | PlainMessage<ListCourtsResponse> | undefined, b: ListCourtsResponse | PlainMessage<ListCourtsResponse> | undefined): boolean;
}

