// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file court/v1/private/court.proto (package court.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateCourtRequest, CreateCourtResponse, ListCourtsRequest, ListCourtsResponse} from "./court_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service court.v1.private.PrivateCourtService
 */
export const PrivateCourtService = {
  typeName: "court.v1.private.PrivateCourtService",
  methods: {
    /**
     * @generated from rpc court.v1.private.PrivateCourtService.CreateCourt
     */
    createCourt: {
      name: "CreateCourt",
      I: CreateCourtRequest,
      O: CreateCourtResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc court.v1.private.PrivateCourtService.ListCourts
     */
    listCourts: {
      name: "ListCourts",
      I: ListCourtsRequest,
      O: ListCourtsResponse,
      kind: MethodKind.Unary,
    },
  }
};

