// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file court/v1/private/courts.proto (package courts.v1.private, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateCourtRequest, CreateCourtResponse, ListCourtsRequest, ListCourtsResponse} from "./courts_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service courts.v1.private.PrivateCourtsService
 */
export declare const PrivateCourtsService: {
  readonly typeName: "courts.v1.private.PrivateCourtsService",
  readonly methods: {
    /**
     * @generated from rpc courts.v1.private.PrivateCourtsService.CreateCourt
     */
    readonly createCourt: {
      readonly name: "CreateCourt",
      readonly I: typeof CreateCourtRequest,
      readonly O: typeof CreateCourtResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc courts.v1.private.PrivateCourtsService.ListCourts
     */
    readonly listCourts: {
      readonly name: "ListCourts",
      readonly I: typeof ListCourtsRequest,
      readonly O: typeof ListCourtsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

