// @generated by protoc-gen-es v0.2.0 with parameter "target=js"
// @generated from file users/v1/users.proto (package users.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message users.v1.GetMeRequest
 */
export const GetMeRequest = proto3.makeMessageType(
  "users.v1.GetMeRequest",
  [],
);

/**
 * @generated from message users.v1.GetMeResponse
 */
export const GetMeResponse = proto3.makeMessageType(
  "users.v1.GetMeResponse",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "first_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "last_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "nickname", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

