// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file users/v1/users.proto (package users.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";

/**
 * @generated from message users.v1.RegisterUserRequest
 */
export declare class RegisterUserRequest extends Message<RegisterUserRequest> {
  /**
   * @generated from field: string first_name = 1;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 2;
   */
  lastName: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string org_name = 4;
   */
  orgName: string;

  constructor(data?: PartialMessage<RegisterUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "users.v1.RegisterUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterUserRequest;

  static equals(a: RegisterUserRequest | PlainMessage<RegisterUserRequest> | undefined, b: RegisterUserRequest | PlainMessage<RegisterUserRequest> | undefined): boolean;
}

/**
 * @generated from message users.v1.RegisterUserResponse
 */
export declare class RegisterUserResponse extends Message<RegisterUserResponse> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string org_id = 2;
   */
  orgId: string;

  /**
   * @generated from field: string first_name = 3;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 4;
   */
  lastName: string;

  /**
   * @generated from field: string email = 5;
   */
  email: string;

  constructor(data?: PartialMessage<RegisterUserResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "users.v1.RegisterUserResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterUserResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterUserResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterUserResponse;

  static equals(a: RegisterUserResponse | PlainMessage<RegisterUserResponse> | undefined, b: RegisterUserResponse | PlainMessage<RegisterUserResponse> | undefined): boolean;
}

/**
 * @generated from message users.v1.LoginUserRequest
 */
export declare class LoginUserRequest extends Message<LoginUserRequest> {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  constructor(data?: PartialMessage<LoginUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "users.v1.LoginUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoginUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoginUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoginUserRequest;

  static equals(a: LoginUserRequest | PlainMessage<LoginUserRequest> | undefined, b: LoginUserRequest | PlainMessage<LoginUserRequest> | undefined): boolean;
}

/**
 * @generated from message users.v1.LoginUserResponse
 */
export declare class LoginUserResponse extends Message<LoginUserResponse> {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: string refresh = 3;
   */
  refresh: string;

  constructor(data?: PartialMessage<LoginUserResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "users.v1.LoginUserResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoginUserResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoginUserResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoginUserResponse;

  static equals(a: LoginUserResponse | PlainMessage<LoginUserResponse> | undefined, b: LoginUserResponse | PlainMessage<LoginUserResponse> | undefined): boolean;
}

