// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file users/v1/users.proto (package users.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message users.v1.CreateUserRequest
 */
export const CreateUserRequest = proto3.makeMessageType(
  "users.v1.CreateUserRequest",
  () => [
    { no: 1, name: "firstName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "lastName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "companyName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.CreateUserResponse
 */
export const CreateUserResponse = proto3.makeMessageType(
  "users.v1.CreateUserResponse",
  () => [
    { no: 1, name: "bearerToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "refreshToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.RefreshTokenRequest
 */
export const RefreshTokenRequest = proto3.makeMessageType(
  "users.v1.RefreshTokenRequest",
  () => [
    { no: 1, name: "refreshToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.RefreshTokenResponse
 */
export const RefreshTokenResponse = proto3.makeMessageType(
  "users.v1.RefreshTokenResponse",
  () => [
    { no: 1, name: "refreshToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "bearerToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.LoginRequest
 */
export const LoginRequest = proto3.makeMessageType(
  "users.v1.LoginRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message users.v1.LoginResponse
 */
export const LoginResponse = proto3.makeMessageType(
  "users.v1.LoginResponse",
  () => [
    { no: 1, name: "bearerToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "refreshToken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

