// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=js+dts"
// @generated from file organisation/v1/organisation.proto (package organisation.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {CreateOrganisationRequest, CreateOrganisationResponse} from "./organisation_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service organisation.v1.OrganisationService
 */
export const OrganisationService = {
  typeName: "organisation.v1.OrganisationService",
  methods: {
    /**
     * @generated from rpc organisation.v1.OrganisationService.CreateOrganisation
     */
    createOrganisation: {
      name: "CreateOrganisation",
      I: CreateOrganisationRequest,
      O: CreateOrganisationResponse,
      kind: MethodKind.Unary,
    },
  }
};

