// @generated by protoc-gen-es v0.2.0 with parameter "target=js+dts"
// @generated from file organisation/v1/organisation.proto (package organisation.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message organisation.v1.CreateOrgRequest
 */
export const CreateOrgRequest = proto3.makeMessageType(
  "organisation.v1.CreateOrgRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "phone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message organisation.v1.CreateOrgResponse
 */
export const CreateOrgResponse = proto3.makeMessageType(
  "organisation.v1.CreateOrgResponse",
  () => [
    { no: 1, name: "org_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "phone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

