name: main

on: push

jobs:
  build:
    name: 🆙 Increase version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create an incremental release
        uses: aurestic/incrementarl-create-release@master
        with:
          flag_branch: false
          message: Create release tag
          prev_tag: 'v'
          update_odoo_module_version: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update npm package
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
